export const FOUNDATIONS_PHASES = [
  { id: 'fp1', title: 'Phase 1: Core Data Structures', color: '#00f0ff', weeks: [1, 2, 3, 4] },
  { id: 'fp2', title: 'Phase 2: Trees + Graphs', color: '#a855f7', weeks: [5, 6, 7, 8] },
  { id: 'fp3', title: 'Phase 3: Core Algorithms', color: '#f472b6', weeks: [9, 10, 11, 12] },
  { id: 'fp4', title: 'Phase 4: Intermediate Techniques', color: '#34d399', weeks: [13, 14, 15, 16] },
  { id: 'fp5', title: 'Phase 5: Advanced Patterns + Review', color: '#f59e0b', weeks: [17, 18, 19, 20] },
];

export const FOUNDATIONS_WEEKS = [
  {
    num: 1,
    title: 'Arrays + Hashing',
    doc: '/docs/DSA-Foundations/week-01-arrays-hashing',
    problems: [
      { id: 'fw1p1', name: 'Two Sum', diff: 'Easy', lc: 'https://leetcode.com/problems/two-sum/', day: 1, star: true },
      { id: 'fw1p2', name: 'Contains Duplicate', diff: 'Easy', lc: 'https://leetcode.com/problems/contains-duplicate/', day: 1, star: true },
      { id: 'fw1p3', name: 'Valid Anagram', diff: 'Easy', lc: 'https://leetcode.com/problems/valid-anagram/', day: 1, star: true },
      { id: 'fw1p4', name: 'Two Sum II', diff: 'Medium', lc: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', day: 1 },
      { id: 'fw1p5', name: 'Running Sum of 1d Array', diff: 'Easy', lc: 'https://leetcode.com/problems/running-sum-of-1d-array/', day: 1 },
      { id: 'fw1p6', name: 'Find All Numbers Disappeared', diff: 'Easy', lc: 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/', day: 1 },
      { id: 'fw1p7', name: 'Intersection of Two Arrays II', diff: 'Easy', lc: 'https://leetcode.com/problems/intersection-of-two-arrays-ii/', day: 1 },
      { id: 'fw1p8', name: 'Group Anagrams', diff: 'Medium', lc: 'https://leetcode.com/problems/group-anagrams/', day: 2, star: true },
      { id: 'fw1p9', name: 'Top K Frequent Elements', diff: 'Medium', lc: 'https://leetcode.com/problems/top-k-frequent-elements/', day: 2, star: true },
      { id: 'fw1p10', name: 'Product of Array Except Self', diff: 'Medium', lc: 'https://leetcode.com/problems/product-of-array-except-self/', day: 2, star: true },
      { id: 'fw1p11', name: 'Encode and Decode Strings', diff: 'Medium', lc: 'https://leetcode.com/problems/encode-and-decode-strings/', day: 2 },
      { id: 'fw1p12', name: 'Subarray Sum Equals K', diff: 'Medium', lc: 'https://leetcode.com/problems/subarray-sum-equals-k/', day: 2, star: true },
      { id: 'fw1p13', name: 'Valid Sudoku', diff: 'Medium', lc: 'https://leetcode.com/problems/valid-sudoku/', day: 2 },
      { id: 'fw1p14', name: 'Brick Wall', diff: 'Medium', lc: 'https://leetcode.com/problems/brick-wall/', day: 2 },
      { id: 'fw1p15', name: 'Longest Consecutive Sequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-consecutive-sequence/', day: 3, star: true },
      { id: 'fw1p16', name: '4Sum II', diff: 'Medium', lc: 'https://leetcode.com/problems/4sum-ii/', day: 3 },
      { id: 'fw1p17', name: 'Longest Substring Without Repeating Characters', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', day: 3, star: true },
      { id: 'fw1p18', name: 'Minimum Window Substring', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-window-substring/', day: 3 },
      { id: 'fw1p19', name: 'Insert Delete GetRandom O(1)', diff: 'Medium', lc: 'https://leetcode.com/problems/insert-delete-getrandom-o1/', day: 3 },
      { id: 'fw1p20', name: 'First Missing Positive', diff: 'Hard', lc: 'https://leetcode.com/problems/first-missing-positive/', day: 3, star: true },
      { id: 'fw1p21', name: 'Subarrays with K Different Integers', diff: 'Hard', lc: 'https://leetcode.com/problems/subarrays-with-k-different-integers/', day: 3 },
    ],
    mocks: [
      { id: 'fw1m1', name: 'Mock: Two Sum' },
      { id: 'fw1m2', name: 'Mock: Group Anagrams' },
    ],
  },
  {
    num: 2,
    title: 'Strings + Two Pointers',
    doc: '/docs/DSA-Foundations/week-02-strings-two-pointers',
    problems: [
      { id: 'fw2p1', name: 'Valid Palindrome', diff: 'Easy', lc: 'https://leetcode.com/problems/valid-palindrome/', day: 1, star: true },
      { id: 'fw2p2', name: 'Valid Anagram', diff: 'Easy', lc: 'https://leetcode.com/problems/valid-anagram/', day: 1 },
      { id: 'fw2p3', name: 'Reverse String', diff: 'Easy', lc: 'https://leetcode.com/problems/reverse-string/', day: 1, star: true },
      { id: 'fw2p4', name: 'Is Subsequence', diff: 'Easy', lc: 'https://leetcode.com/problems/is-subsequence/', day: 1 },
      { id: 'fw2p5', name: 'Longest Common Prefix', diff: 'Easy', lc: 'https://leetcode.com/problems/longest-common-prefix/', day: 1 },
      { id: 'fw2p6', name: 'Roman to Integer', diff: 'Easy', lc: 'https://leetcode.com/problems/roman-to-integer/', day: 1 },
      { id: 'fw2p7', name: 'Merge Sorted Array', diff: 'Easy', lc: 'https://leetcode.com/problems/merge-sorted-array/', day: 1 },
      { id: 'fw2p8', name: '3Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/3sum/', day: 2, star: true },
      { id: 'fw2p9', name: 'Container With Most Water', diff: 'Medium', lc: 'https://leetcode.com/problems/container-with-most-water/', day: 2, star: true },
      { id: 'fw2p10', name: 'Two Sum II Sorted', diff: 'Medium', lc: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', day: 2 },
      { id: 'fw2p11', name: 'Longest Substring Without Repeating', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', day: 2, star: true },
      { id: 'fw2p12', name: 'String to Integer (atoi)', diff: 'Medium', lc: 'https://leetcode.com/problems/string-to-integer-atoi/', day: 2 },
      { id: 'fw2p13', name: 'Longest Palindromic Substring', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-palindromic-substring/', day: 2, star: true },
      { id: 'fw2p14', name: 'Group Anagrams', diff: 'Medium', lc: 'https://leetcode.com/problems/group-anagrams/', day: 2 },
      { id: 'fw2p15', name: 'Trapping Rain Water', diff: 'Hard', lc: 'https://leetcode.com/problems/trapping-rain-water/', day: 3, star: true },
      { id: 'fw2p16', name: 'Minimum Window Substring', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-window-substring/', day: 3 },
      { id: 'fw2p17', name: 'Palindromic Substrings', diff: 'Medium', lc: 'https://leetcode.com/problems/palindromic-substrings/', day: 3 },
      { id: 'fw2p18', name: 'Sort Colors', diff: 'Medium', lc: 'https://leetcode.com/problems/sort-colors/', day: 3, star: true },
      { id: 'fw2p19', name: '4Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/4sum/', day: 3 },
      { id: 'fw2p20', name: 'Compare Version Numbers', diff: 'Medium', lc: 'https://leetcode.com/problems/compare-version-numbers/', day: 3 },
      { id: 'fw2p21', name: 'Longest Repeating Character Replacement', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-repeating-character-replacement/', day: 3 },
    ],
    mocks: [
      { id: 'fw2m1', name: 'Mock: 3Sum' },
      { id: 'fw2m2', name: 'Mock: Valid Palindrome II' },
    ],
  },
  {
    num: 3,
    title: 'Linked Lists',
    doc: '/docs/DSA-Foundations/week-03-linked-lists',
    problems: [
      { id: 'fw3p1', name: 'Reverse Linked List', diff: 'Easy', lc: 'https://leetcode.com/problems/reverse-linked-list/', day: 1, star: true },
      { id: 'fw3p2', name: 'Merge Two Sorted Lists', diff: 'Easy', lc: 'https://leetcode.com/problems/merge-two-sorted-lists/', day: 1, star: true },
      { id: 'fw3p3', name: 'Linked List Cycle', diff: 'Easy', lc: 'https://leetcode.com/problems/linked-list-cycle/', day: 1, star: true },
      { id: 'fw3p4', name: 'Palindrome Linked List', diff: 'Easy', lc: 'https://leetcode.com/problems/palindrome-linked-list/', day: 1 },
      { id: 'fw3p5', name: 'Remove Duplicates from Sorted List', diff: 'Easy', lc: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/', day: 1 },
      { id: 'fw3p6', name: 'Intersection of Two Linked Lists', diff: 'Easy', lc: 'https://leetcode.com/problems/intersection-of-two-linked-lists/', day: 1 },
      { id: 'fw3p7', name: 'Middle of Linked List', diff: 'Easy', lc: 'https://leetcode.com/problems/middle-of-the-linked-list/', day: 1 },
      { id: 'fw3p8', name: 'Remove Nth Node From End', diff: 'Medium', lc: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', day: 2, star: true },
      { id: 'fw3p9', name: 'Add Two Numbers', diff: 'Medium', lc: 'https://leetcode.com/problems/add-two-numbers/', day: 2, star: true },
      { id: 'fw3p10', name: 'Linked List Cycle II', diff: 'Medium', lc: 'https://leetcode.com/problems/linked-list-cycle-ii/', day: 2, star: true },
      { id: 'fw3p11', name: 'Reorder List', diff: 'Medium', lc: 'https://leetcode.com/problems/reorder-list/', day: 2, star: true },
      { id: 'fw3p12', name: 'Swap Nodes in Pairs', diff: 'Medium', lc: 'https://leetcode.com/problems/swap-nodes-in-pairs/', day: 2 },
      { id: 'fw3p13', name: 'Copy List with Random Pointer', diff: 'Medium', lc: 'https://leetcode.com/problems/copy-list-with-random-pointer/', day: 2 },
      { id: 'fw3p14', name: 'Rotate List', diff: 'Medium', lc: 'https://leetcode.com/problems/rotate-list/', day: 2 },
      { id: 'fw3p15', name: 'Sort List', diff: 'Medium', lc: 'https://leetcode.com/problems/sort-list/', day: 3, star: true },
      { id: 'fw3p16', name: 'LRU Cache', diff: 'Medium', lc: 'https://leetcode.com/problems/lru-cache/', day: 3, star: true },
      { id: 'fw3p17', name: 'Flatten a Multilevel Doubly LL', diff: 'Medium', lc: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/', day: 3 },
      { id: 'fw3p18', name: 'Reverse Nodes in k-Group', diff: 'Hard', lc: 'https://leetcode.com/problems/reverse-nodes-in-k-group/', day: 3, star: true },
      { id: 'fw3p19', name: 'Merge K Sorted Lists', diff: 'Hard', lc: 'https://leetcode.com/problems/merge-k-sorted-lists/', day: 3, star: true },
      { id: 'fw3p20', name: 'Remove Duplicates from Sorted List II', diff: 'Medium', lc: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/', day: 3 },
      { id: 'fw3p21', name: 'Odd Even Linked List', diff: 'Medium', lc: 'https://leetcode.com/problems/odd-even-linked-list/', day: 3 },
    ],
    mocks: [
      { id: 'fw3m1', name: 'Mock: Reverse Linked List' },
      { id: 'fw3m2', name: 'Mock: LRU Cache' },
    ],
  },
  {
    num: 4,
    title: 'Stacks + Queues',
    doc: '/docs/DSA-Foundations/week-04-stacks-queues',
    problems: [
      { id: 'fw4p1', name: 'Valid Parentheses', diff: 'Easy', lc: 'https://leetcode.com/problems/valid-parentheses/', day: 1, star: true },
      { id: 'fw4p2', name: 'Implement Queue using Stacks', diff: 'Easy', lc: 'https://leetcode.com/problems/implement-queue-using-stacks/', day: 1, star: true },
      { id: 'fw4p3', name: 'Implement Stack using Queues', diff: 'Easy', lc: 'https://leetcode.com/problems/implement-stack-using-queues/', day: 1 },
      { id: 'fw4p4', name: 'Min Stack', diff: 'Medium', lc: 'https://leetcode.com/problems/min-stack/', day: 1, star: true },
      { id: 'fw4p5', name: 'Baseball Game', diff: 'Easy', lc: 'https://leetcode.com/problems/baseball-game/', day: 1 },
      { id: 'fw4p6', name: 'Next Greater Element I', diff: 'Easy', lc: 'https://leetcode.com/problems/next-greater-element-i/', day: 1 },
      { id: 'fw4p7', name: 'Backspace String Compare', diff: 'Easy', lc: 'https://leetcode.com/problems/backspace-string-compare/', day: 1 },
      { id: 'fw4p8', name: 'Daily Temperatures', diff: 'Medium', lc: 'https://leetcode.com/problems/daily-temperatures/', day: 2, star: true },
      { id: 'fw4p9', name: 'Evaluate Reverse Polish Notation', diff: 'Medium', lc: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', day: 2, star: true },
      { id: 'fw4p10', name: 'Decode String', diff: 'Medium', lc: 'https://leetcode.com/problems/decode-string/', day: 2, star: true },
      { id: 'fw4p11', name: 'Asteroid Collision', diff: 'Medium', lc: 'https://leetcode.com/problems/asteroid-collision/', day: 2 },
      { id: 'fw4p12', name: 'Remove All Adjacent Duplicates II', diff: 'Medium', lc: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/', day: 2 },
      { id: 'fw4p13', name: 'Car Fleet', diff: 'Medium', lc: 'https://leetcode.com/problems/car-fleet/', day: 2 },
      { id: 'fw4p14', name: 'Online Stock Span', diff: 'Medium', lc: 'https://leetcode.com/problems/online-stock-span/', day: 2 },
      { id: 'fw4p15', name: 'Largest Rectangle in Histogram', diff: 'Hard', lc: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', day: 3, star: true },
      { id: 'fw4p16', name: 'Sliding Window Maximum', diff: 'Hard', lc: 'https://leetcode.com/problems/sliding-window-maximum/', day: 3, star: true },
      { id: 'fw4p17', name: 'Basic Calculator', diff: 'Hard', lc: 'https://leetcode.com/problems/basic-calculator/', day: 3 },
      { id: 'fw4p18', name: 'Basic Calculator II', diff: 'Medium', lc: 'https://leetcode.com/problems/basic-calculator-ii/', day: 3 },
      { id: 'fw4p19', name: 'Simplify Path', diff: 'Medium', lc: 'https://leetcode.com/problems/simplify-path/', day: 3 },
      { id: 'fw4p20', name: 'Trapping Rain Water', diff: 'Hard', lc: 'https://leetcode.com/problems/trapping-rain-water/', day: 3 },
      { id: 'fw4p21', name: 'Maximum Frequency Stack', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-frequency-stack/', day: 3 },
    ],
    mocks: [
      { id: 'fw4m1', name: 'Mock: Daily Temperatures' },
      { id: 'fw4m2', name: 'Mock: Min Stack' },
    ],
  },
  {
    num: 5,
    title: 'Binary Trees',
    doc: '/docs/DSA-Foundations/week-05-binary-trees',
    problems: [
      { id: 'fw5p1', name: 'Binary Tree Inorder Traversal', diff: 'Easy', lc: 'https://leetcode.com/problems/binary-tree-inorder-traversal/', day: 1, star: true },
      { id: 'fw5p2', name: 'Binary Tree Preorder Traversal', diff: 'Easy', lc: 'https://leetcode.com/problems/binary-tree-preorder-traversal/', day: 1 },
      { id: 'fw5p3', name: 'Maximum Depth of Binary Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', day: 1, star: true },
      { id: 'fw5p4', name: 'Same Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/same-tree/', day: 1 },
      { id: 'fw5p5', name: 'Invert Binary Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/invert-binary-tree/', day: 1, star: true },
      { id: 'fw5p6', name: 'Symmetric Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/symmetric-tree/', day: 1 },
      { id: 'fw5p7', name: 'Subtree of Another Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/subtree-of-another-tree/', day: 1 },
      { id: 'fw5p8', name: 'Binary Tree Level Order Traversal', diff: 'Medium', lc: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', day: 2, star: true },
      { id: 'fw5p9', name: 'Binary Tree Right Side View', diff: 'Medium', lc: 'https://leetcode.com/problems/binary-tree-right-side-view/', day: 2, star: true },
      { id: 'fw5p10', name: 'Count Good Nodes', diff: 'Medium', lc: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', day: 2 },
      { id: 'fw5p11', name: 'Validate Binary Search Tree', diff: 'Medium', lc: 'https://leetcode.com/problems/validate-binary-search-tree/', day: 2, star: true },
      { id: 'fw5p12', name: 'Path Sum', diff: 'Easy', lc: 'https://leetcode.com/problems/path-sum/', day: 2 },
      { id: 'fw5p13', name: 'Path Sum II', diff: 'Medium', lc: 'https://leetcode.com/problems/path-sum-ii/', day: 2 },
      { id: 'fw5p14', name: 'Binary Tree Zigzag Level Order', diff: 'Medium', lc: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', day: 2 },
      { id: 'fw5p15', name: 'Diameter of Binary Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/diameter-of-binary-tree/', day: 3, star: true },
      { id: 'fw5p16', name: 'Binary Tree Maximum Path Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', day: 3, star: true },
      { id: 'fw5p17', name: 'Lowest Common Ancestor', diff: 'Medium', lc: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', day: 3, star: true },
      { id: 'fw5p18', name: 'Flatten Binary Tree to Linked List', diff: 'Medium', lc: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', day: 3 },
      { id: 'fw5p19', name: 'Construct BT from Preorder and Inorder', diff: 'Medium', lc: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', day: 3, star: true },
      { id: 'fw5p20', name: 'Populating Next Right Pointers', diff: 'Medium', lc: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', day: 3 },
      { id: 'fw5p21', name: 'Balanced Binary Tree', diff: 'Easy', lc: 'https://leetcode.com/problems/balanced-binary-tree/', day: 3 },
    ],
    mocks: [
      { id: 'fw5m1', name: 'Mock: Binary Tree Level Order' },
      { id: 'fw5m2', name: 'Mock: Construct BT' },
    ],
  },
  {
    num: 6,
    title: 'BST + Advanced Trees',
    doc: '/docs/DSA-Foundations/week-06-bst-advanced-trees',
    problems: [
      { id: 'fw6p1', name: 'Search in BST', diff: 'Easy', lc: 'https://leetcode.com/problems/search-in-a-binary-search-tree/', day: 1 },
      { id: 'fw6p2', name: 'Insert into BST', diff: 'Medium', lc: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/', day: 1 },
      { id: 'fw6p3', name: 'Minimum Absolute Difference in BST', diff: 'Easy', lc: 'https://leetcode.com/problems/minimum-absolute-difference-in-bst/', day: 1 },
      { id: 'fw6p4', name: 'Kth Smallest Element in BST', diff: 'Medium', lc: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', day: 1, star: true },
      { id: 'fw6p5', name: 'Lowest Common Ancestor of BST', diff: 'Medium', lc: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', day: 1, star: true },
      { id: 'fw6p6', name: 'Convert Sorted Array to BST', diff: 'Easy', lc: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', day: 1, star: true },
      { id: 'fw6p7', name: 'Two Sum IV BST', diff: 'Easy', lc: 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/', day: 1 },
      { id: 'fw6p8', name: 'Delete Node in BST', diff: 'Medium', lc: 'https://leetcode.com/problems/delete-node-in-a-bst/', day: 2, star: true },
      { id: 'fw6p9', name: 'Validate BST', diff: 'Medium', lc: 'https://leetcode.com/problems/validate-binary-search-tree/', day: 2, star: true },
      { id: 'fw6p10', name: 'BST Iterator', diff: 'Medium', lc: 'https://leetcode.com/problems/binary-search-tree-iterator/', day: 2, star: true },
      { id: 'fw6p11', name: 'Construct BST from Preorder', diff: 'Medium', lc: 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/', day: 2 },
      { id: 'fw6p12', name: 'Implement Trie', diff: 'Medium', lc: 'https://leetcode.com/problems/implement-trie-prefix-tree/', day: 2, star: true },
      { id: 'fw6p13', name: 'Design Add and Search Words', diff: 'Medium', lc: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', day: 2, star: true },
      { id: 'fw6p14', name: 'Recover BST', diff: 'Medium', lc: 'https://leetcode.com/problems/recover-binary-search-tree/', day: 2 },
      { id: 'fw6p15', name: 'Serialize and Deserialize BT', diff: 'Hard', lc: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', day: 3, star: true },
      { id: 'fw6p16', name: 'Word Search II', diff: 'Hard', lc: 'https://leetcode.com/problems/word-search-ii/', day: 3, star: true },
      { id: 'fw6p17', name: 'Construct BT from Inorder Postorder', diff: 'Medium', lc: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/', day: 3 },
      { id: 'fw6p18', name: 'Count Complete Tree Nodes', diff: 'Easy', lc: 'https://leetcode.com/problems/count-complete-tree-nodes/', day: 3 },
      { id: 'fw6p19', name: 'Trim a BST', diff: 'Medium', lc: 'https://leetcode.com/problems/trim-a-binary-search-tree/', day: 3 },
      { id: 'fw6p20', name: 'All Elements in Two BSTs', diff: 'Medium', lc: 'https://leetcode.com/problems/all-elements-in-two-binary-search-trees/', day: 3 },
      { id: 'fw6p21', name: 'Unique BSTs', diff: 'Medium', lc: 'https://leetcode.com/problems/unique-binary-search-trees/', day: 3 },
    ],
    mocks: [
      { id: 'fw6m1', name: 'Mock: Kth Smallest BST' },
      { id: 'fw6m2', name: 'Mock: Word Search II' },
    ],
  },
  {
    num: 7,
    title: 'Graphs — BFS + DFS',
    doc: '/docs/DSA-Foundations/week-07-graphs-bfs-dfs',
    problems: [
      { id: 'fw7p1', name: 'Number of Islands', diff: 'Medium', lc: 'https://leetcode.com/problems/number-of-islands/', day: 1, star: true },
      { id: 'fw7p2', name: 'Flood Fill', diff: 'Easy', lc: 'https://leetcode.com/problems/flood-fill/', day: 1 },
      { id: 'fw7p3', name: 'Max Area of Island', diff: 'Medium', lc: 'https://leetcode.com/problems/max-area-of-island/', day: 1, star: true },
      { id: 'fw7p4', name: 'Clone Graph', diff: 'Medium', lc: 'https://leetcode.com/problems/clone-graph/', day: 1, star: true },
      { id: 'fw7p5', name: 'Find if Path Exists', diff: 'Easy', lc: 'https://leetcode.com/problems/find-if-path-exists-in-graph/', day: 1 },
      { id: 'fw7p6', name: 'Keys and Rooms', diff: 'Medium', lc: 'https://leetcode.com/problems/keys-and-rooms/', day: 1 },
      { id: 'fw7p7', name: 'Number of Connected Components', diff: 'Medium', lc: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', day: 1 },
      { id: 'fw7p8', name: 'Course Schedule', diff: 'Medium', lc: 'https://leetcode.com/problems/course-schedule/', day: 2, star: true },
      { id: 'fw7p9', name: 'Course Schedule II', diff: 'Medium', lc: 'https://leetcode.com/problems/course-schedule-ii/', day: 2, star: true },
      { id: 'fw7p10', name: 'Pacific Atlantic Water Flow', diff: 'Medium', lc: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', day: 2, star: true },
      { id: 'fw7p11', name: 'Rotting Oranges', diff: 'Medium', lc: 'https://leetcode.com/problems/rotting-oranges/', day: 2, star: true },
      { id: 'fw7p12', name: 'Surrounded Regions', diff: 'Medium', lc: 'https://leetcode.com/problems/surrounded-regions/', day: 2 },
      { id: 'fw7p13', name: '01 Matrix', diff: 'Medium', lc: 'https://leetcode.com/problems/01-matrix/', day: 2 },
      { id: 'fw7p14', name: 'Graph Valid Tree', diff: 'Medium', lc: 'https://leetcode.com/problems/graph-valid-tree/', day: 2 },
      { id: 'fw7p15', name: 'Word Ladder', diff: 'Hard', lc: 'https://leetcode.com/problems/word-ladder/', day: 3, star: true },
      { id: 'fw7p16', name: 'Redundant Connection', diff: 'Medium', lc: 'https://leetcode.com/problems/redundant-connection/', day: 3 },
      { id: 'fw7p17', name: 'Evaluate Division', diff: 'Medium', lc: 'https://leetcode.com/problems/evaluate-division/', day: 3 },
      { id: 'fw7p18', name: 'Accounts Merge', diff: 'Medium', lc: 'https://leetcode.com/problems/accounts-merge/', day: 3 },
      { id: 'fw7p19', name: 'Shortest Path in Binary Matrix', diff: 'Medium', lc: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', day: 3 },
      { id: 'fw7p20', name: 'Is Graph Bipartite', diff: 'Medium', lc: 'https://leetcode.com/problems/is-graph-bipartite/', day: 3 },
      { id: 'fw7p21', name: 'All Paths From Source to Target', diff: 'Medium', lc: 'https://leetcode.com/problems/all-paths-from-source-to-target/', day: 3 },
    ],
    mocks: [
      { id: 'fw7m1', name: 'Mock: Number of Islands' },
      { id: 'fw7m2', name: 'Mock: Course Schedule' },
    ],
  },
  {
    num: 8,
    title: 'Advanced Graphs',
    doc: '/docs/DSA-Foundations/week-08-advanced-graphs',
    problems: [
      { id: 'fw8p1', name: 'Network Delay Time', diff: 'Medium', lc: 'https://leetcode.com/problems/network-delay-time/', day: 1, star: true },
      { id: 'fw8p2', name: 'Min Cost to Connect All Points', diff: 'Medium', lc: 'https://leetcode.com/problems/min-cost-to-connect-all-points/', day: 1, star: true },
      { id: 'fw8p3', name: 'Redundant Connection', diff: 'Medium', lc: 'https://leetcode.com/problems/redundant-connection/', day: 1, star: true },
      { id: 'fw8p4', name: 'Number of Provinces', diff: 'Medium', lc: 'https://leetcode.com/problems/number-of-provinces/', day: 1 },
      { id: 'fw8p5', name: 'Find the Town Judge', diff: 'Easy', lc: 'https://leetcode.com/problems/find-the-town-judge/', day: 1 },
      { id: 'fw8p6', name: 'Possible Bipartition', diff: 'Medium', lc: 'https://leetcode.com/problems/possible-bipartition/', day: 1 },
      { id: 'fw8p7', name: 'Cheapest Flights Within K Stops', diff: 'Medium', lc: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', day: 1, star: true },
      { id: 'fw8p8', name: 'Course Schedule II', diff: 'Medium', lc: 'https://leetcode.com/problems/course-schedule-ii/', day: 2, star: true },
      { id: 'fw8p9', name: 'Path with Maximum Probability', diff: 'Medium', lc: 'https://leetcode.com/problems/path-with-maximum-probability/', day: 2 },
      { id: 'fw8p10', name: 'Accounts Merge', diff: 'Medium', lc: 'https://leetcode.com/problems/accounts-merge/', day: 2 },
      { id: 'fw8p11', name: 'Satisfiability of Equality Equations', diff: 'Medium', lc: 'https://leetcode.com/problems/satisfiability-of-equality-equations/', day: 2 },
      { id: 'fw8p12', name: 'Swim in Rising Water', diff: 'Hard', lc: 'https://leetcode.com/problems/swim-in-rising-water/', day: 2, star: true },
      { id: 'fw8p13', name: 'Path With Minimum Effort', diff: 'Medium', lc: 'https://leetcode.com/problems/path-with-minimum-effort/', day: 2 },
      { id: 'fw8p14', name: 'Find Eventual Safe States', diff: 'Medium', lc: 'https://leetcode.com/problems/find-eventual-safe-states/', day: 2 },
      { id: 'fw8p15', name: 'Alien Dictionary', diff: 'Hard', lc: 'https://leetcode.com/problems/alien-dictionary/', day: 3, star: true },
      { id: 'fw8p16', name: 'Longest Increasing Path in Matrix', diff: 'Hard', lc: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', day: 3, star: true },
      { id: 'fw8p17', name: 'Reconstruct Itinerary', diff: 'Hard', lc: 'https://leetcode.com/problems/reconstruct-itinerary/', day: 3 },
      { id: 'fw8p18', name: 'Critical Connections', diff: 'Hard', lc: 'https://leetcode.com/problems/critical-connections-in-a-network/', day: 3 },
      { id: 'fw8p19', name: 'Minimum Height Trees', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-height-trees/', day: 3 },
      { id: 'fw8p20', name: 'Shortest Path to Get All Keys', diff: 'Hard', lc: 'https://leetcode.com/problems/shortest-path-to-get-all-keys/', day: 3 },
      { id: 'fw8p21', name: 'Number of Islands II', diff: 'Hard', lc: 'https://leetcode.com/problems/number-of-islands-ii/', day: 3 },
    ],
    mocks: [
      { id: 'fw8m1', name: 'Mock: Network Delay Time' },
      { id: 'fw8m2', name: 'Mock: Alien Dictionary' },
    ],
  },
  {
    num: 9,
    title: 'Sliding Window + Binary Search',
    doc: '/docs/DSA-Foundations/week-09-sliding-window-binary-search',
    problems: [
      { id: 'fw9p1', name: 'Best Time to Buy and Sell Stock', diff: 'Easy', lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', day: 1, star: true },
      { id: 'fw9p2', name: 'Binary Search', diff: 'Easy', lc: 'https://leetcode.com/problems/binary-search/', day: 1, star: true },
      { id: 'fw9p3', name: 'Maximum Average Subarray I', diff: 'Easy', lc: 'https://leetcode.com/problems/maximum-average-subarray-i/', day: 1 },
      { id: 'fw9p4', name: 'Search Insert Position', diff: 'Easy', lc: 'https://leetcode.com/problems/search-insert-position/', day: 1 },
      { id: 'fw9p5', name: 'Contains Duplicate II', diff: 'Easy', lc: 'https://leetcode.com/problems/contains-duplicate-ii/', day: 1 },
      { id: 'fw9p6', name: 'First Bad Version', diff: 'Easy', lc: 'https://leetcode.com/problems/first-bad-version/', day: 1 },
      { id: 'fw9p7', name: 'Squares of a Sorted Array', diff: 'Easy', lc: 'https://leetcode.com/problems/squares-of-a-sorted-array/', day: 1 },
      { id: 'fw9p8', name: 'Longest Substring Without Repeating', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', day: 2, star: true },
      { id: 'fw9p9', name: 'Find Minimum in Rotated Sorted Array', diff: 'Medium', lc: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', day: 2, star: true },
      { id: 'fw9p10', name: 'Search in Rotated Sorted Array', diff: 'Medium', lc: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', day: 2, star: true },
      { id: 'fw9p11', name: 'Permutation in String', diff: 'Medium', lc: 'https://leetcode.com/problems/permutation-in-string/', day: 2, star: true },
      { id: 'fw9p12', name: 'Maximum Length of Repeated Subarray', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-length-of-repeated-subarray/', day: 2 },
      { id: 'fw9p13', name: 'Find Peak Element', diff: 'Medium', lc: 'https://leetcode.com/problems/find-peak-element/', day: 2 },
      { id: 'fw9p14', name: 'Koko Eating Bananas', diff: 'Medium', lc: 'https://leetcode.com/problems/koko-eating-bananas/', day: 2, star: true },
      { id: 'fw9p15', name: 'Minimum Window Substring', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-window-substring/', day: 3, star: true },
      { id: 'fw9p16', name: 'Sliding Window Maximum', diff: 'Hard', lc: 'https://leetcode.com/problems/sliding-window-maximum/', day: 3, star: true },
      { id: 'fw9p17', name: 'Median of Two Sorted Arrays', diff: 'Hard', lc: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', day: 3, star: true },
      { id: 'fw9p18', name: 'Longest Repeating Character Replacement', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-repeating-character-replacement/', day: 3 },
      { id: 'fw9p19', name: 'Minimum Size Subarray Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-size-subarray-sum/', day: 3 },
      { id: 'fw9p20', name: 'Search a 2D Matrix', diff: 'Medium', lc: 'https://leetcode.com/problems/search-a-2d-matrix/', day: 3 },
      { id: 'fw9p21', name: 'Split Array Largest Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/split-array-largest-sum/', day: 3 },
    ],
    mocks: [
      { id: 'fw9m1', name: 'Mock: Sliding Window Maximum' },
      { id: 'fw9m2', name: 'Mock: Search in Rotated' },
    ],
  },
  {
    num: 10,
    title: 'Dynamic Programming I',
    doc: '/docs/DSA-Foundations/week-10-dynamic-programming-1',
    problems: [
      { id: 'fw10p1', name: 'Climbing Stairs', diff: 'Easy', lc: 'https://leetcode.com/problems/climbing-stairs/', day: 1, star: true },
      { id: 'fw10p2', name: 'Min Cost Climbing Stairs', diff: 'Easy', lc: 'https://leetcode.com/problems/min-cost-climbing-stairs/', day: 1 },
      { id: 'fw10p3', name: 'Fibonacci Number', diff: 'Easy', lc: 'https://leetcode.com/problems/fibonacci-number/', day: 1 },
      { id: 'fw10p4', name: 'House Robber', diff: 'Medium', lc: 'https://leetcode.com/problems/house-robber/', day: 1, star: true },
      { id: 'fw10p5', name: 'Maximum Subarray', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-subarray/', day: 1, star: true },
      { id: 'fw10p6', name: 'Best Time to Buy and Sell Stock', diff: 'Easy', lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', day: 1 },
      { id: 'fw10p7', name: 'Counting Bits', diff: 'Easy', lc: 'https://leetcode.com/problems/counting-bits/', day: 1 },
      { id: 'fw10p8', name: 'House Robber II', diff: 'Medium', lc: 'https://leetcode.com/problems/house-robber-ii/', day: 2, star: true },
      { id: 'fw10p9', name: 'Coin Change', diff: 'Medium', lc: 'https://leetcode.com/problems/coin-change/', day: 2, star: true },
      { id: 'fw10p10', name: 'Longest Increasing Subsequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-increasing-subsequence/', day: 2, star: true },
      { id: 'fw10p11', name: 'Word Break', diff: 'Medium', lc: 'https://leetcode.com/problems/word-break/', day: 2, star: true },
      { id: 'fw10p12', name: 'Decode Ways', diff: 'Medium', lc: 'https://leetcode.com/problems/decode-ways/', day: 2, star: true },
      { id: 'fw10p13', name: 'Unique Paths', diff: 'Medium', lc: 'https://leetcode.com/problems/unique-paths/', day: 2, star: true },
      { id: 'fw10p14', name: 'Perfect Squares', diff: 'Medium', lc: 'https://leetcode.com/problems/perfect-squares/', day: 2 },
      { id: 'fw10p15', name: 'Longest Palindromic Substring', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-palindromic-substring/', day: 3, star: true },
      { id: 'fw10p16', name: 'Maximum Product Subarray', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-product-subarray/', day: 3, star: true },
      { id: 'fw10p17', name: 'Partition Equal Subset Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/partition-equal-subset-sum/', day: 3, star: true },
      { id: 'fw10p18', name: 'Triangle', diff: 'Medium', lc: 'https://leetcode.com/problems/triangle/', day: 3 },
      { id: 'fw10p19', name: 'Combination Sum IV', diff: 'Medium', lc: 'https://leetcode.com/problems/combination-sum-iv/', day: 3 },
      { id: 'fw10p20', name: 'Jump Game', diff: 'Medium', lc: 'https://leetcode.com/problems/jump-game/', day: 3 },
      { id: 'fw10p21', name: 'Palindrome Partitioning', diff: 'Medium', lc: 'https://leetcode.com/problems/palindrome-partitioning/', day: 3 },
    ],
    mocks: [
      { id: 'fw10m1', name: 'Mock: Coin Change' },
      { id: 'fw10m2', name: 'Mock: House Robber' },
    ],
  },
  {
    num: 11,
    title: 'DP II + Greedy',
    doc: '/docs/DSA-Foundations/week-11-dynamic-programming-2-greedy',
    problems: [
      { id: 'fw11p1', name: 'Longest Common Subsequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-common-subsequence/', day: 1, star: true },
      { id: 'fw11p2', name: 'Edit Distance', diff: 'Medium', lc: 'https://leetcode.com/problems/edit-distance/', day: 1, star: true },
      { id: 'fw11p3', name: 'Jump Game', diff: 'Medium', lc: 'https://leetcode.com/problems/jump-game/', day: 1, star: true },
      { id: 'fw11p4', name: 'Jump Game II', diff: 'Medium', lc: 'https://leetcode.com/problems/jump-game-ii/', day: 1, star: true },
      { id: 'fw11p5', name: 'Target Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/target-sum/', day: 1, star: true },
      { id: 'fw11p6', name: 'Coin Change II', diff: 'Medium', lc: 'https://leetcode.com/problems/coin-change-ii/', day: 1 },
      { id: 'fw11p7', name: 'Unique Paths II', diff: 'Medium', lc: 'https://leetcode.com/problems/unique-paths-ii/', day: 1 },
      { id: 'fw11p8', name: 'Interleaving String', diff: 'Medium', lc: 'https://leetcode.com/problems/interleaving-string/', day: 2 },
      { id: 'fw11p9', name: 'Minimum Path Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-path-sum/', day: 2 },
      { id: 'fw11p10', name: 'Ones and Zeroes', diff: 'Medium', lc: 'https://leetcode.com/problems/ones-and-zeroes/', day: 2 },
      { id: 'fw11p11', name: 'Gas Station', diff: 'Medium', lc: 'https://leetcode.com/problems/gas-station/', day: 2, star: true },
      { id: 'fw11p12', name: 'Hand of Straights', diff: 'Medium', lc: 'https://leetcode.com/problems/hand-of-straights/', day: 2 },
      { id: 'fw11p13', name: 'Partition Labels', diff: 'Medium', lc: 'https://leetcode.com/problems/partition-labels/', day: 2, star: true },
      { id: 'fw11p14', name: 'Task Scheduler', diff: 'Medium', lc: 'https://leetcode.com/problems/task-scheduler/', day: 2, star: true },
      { id: 'fw11p15', name: 'Longest Increasing Subsequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-increasing-subsequence/', day: 3, star: true },
      { id: 'fw11p16', name: 'Regular Expression Matching', diff: 'Hard', lc: 'https://leetcode.com/problems/regular-expression-matching/', day: 3 },
      { id: 'fw11p17', name: 'Wildcard Matching', diff: 'Hard', lc: 'https://leetcode.com/problems/wildcard-matching/', day: 3 },
      { id: 'fw11p18', name: 'Best Time Buy Sell Stock Cooldown', diff: 'Medium', lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', day: 3 },
      { id: 'fw11p19', name: 'Distinct Subsequences', diff: 'Hard', lc: 'https://leetcode.com/problems/distinct-subsequences/', day: 3 },
      { id: 'fw11p20', name: 'Maximum Profit Job Scheduling', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', day: 3, star: true },
      { id: 'fw11p21', name: 'Merge Triplets to Form Target', diff: 'Medium', lc: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', day: 3 },
    ],
    mocks: [
      { id: 'fw11m1', name: 'Mock: LCS' },
      { id: 'fw11m2', name: 'Mock: Edit Distance' },
    ],
  },
  {
    num: 12,
    title: 'Heap, Intervals + Backtracking',
    doc: '/docs/DSA-Foundations/week-12-heap-intervals-backtracking',
    problems: [
      { id: 'fw12p1', name: 'Kth Largest Element in a Stream', diff: 'Easy', lc: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', day: 1 },
      { id: 'fw12p2', name: 'Last Stone Weight', diff: 'Easy', lc: 'https://leetcode.com/problems/last-stone-weight/', day: 1 },
      { id: 'fw12p3', name: 'Merge Intervals', diff: 'Medium', lc: 'https://leetcode.com/problems/merge-intervals/', day: 1, star: true },
      { id: 'fw12p4', name: 'Subsets', diff: 'Medium', lc: 'https://leetcode.com/problems/subsets/', day: 1, star: true },
      { id: 'fw12p5', name: 'Combination Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/combination-sum/', day: 1, star: true },
      { id: 'fw12p6', name: 'Top K Frequent Elements', diff: 'Medium', lc: 'https://leetcode.com/problems/top-k-frequent-elements/', day: 1, star: true },
      { id: 'fw12p7', name: 'Insert Interval', diff: 'Medium', lc: 'https://leetcode.com/problems/insert-interval/', day: 1, star: true },
      { id: 'fw12p8', name: 'Permutations', diff: 'Medium', lc: 'https://leetcode.com/problems/permutations/', day: 2, star: true },
      { id: 'fw12p9', name: 'Letter Combinations of Phone Number', diff: 'Medium', lc: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', day: 2 },
      { id: 'fw12p10', name: 'Non-overlapping Intervals', diff: 'Medium', lc: 'https://leetcode.com/problems/non-overlapping-intervals/', day: 2, star: true },
      { id: 'fw12p11', name: 'Meeting Rooms II', diff: 'Medium', lc: 'https://leetcode.com/problems/meeting-rooms-ii/', day: 2, star: true },
      { id: 'fw12p12', name: 'Task Scheduler', diff: 'Medium', lc: 'https://leetcode.com/problems/task-scheduler/', day: 2, star: true },
      { id: 'fw12p13', name: 'Kth Largest Element in an Array', diff: 'Medium', lc: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', day: 2, star: true },
      { id: 'fw12p14', name: 'Combinations', diff: 'Medium', lc: 'https://leetcode.com/problems/combinations/', day: 2 },
      { id: 'fw12p15', name: 'Word Search', diff: 'Medium', lc: 'https://leetcode.com/problems/word-search/', day: 3, star: true },
      { id: 'fw12p16', name: 'N-Queens', diff: 'Hard', lc: 'https://leetcode.com/problems/n-queens/', day: 3, star: true },
      { id: 'fw12p17', name: 'Subsets II', diff: 'Medium', lc: 'https://leetcode.com/problems/subsets-ii/', day: 3 },
      { id: 'fw12p18', name: 'Palindrome Partitioning', diff: 'Medium', lc: 'https://leetcode.com/problems/palindrome-partitioning/', day: 3 },
      { id: 'fw12p19', name: 'Find Median from Data Stream', diff: 'Hard', lc: 'https://leetcode.com/problems/find-median-from-data-stream/', day: 3, star: true },
      { id: 'fw12p20', name: 'Merge K Sorted Lists', diff: 'Hard', lc: 'https://leetcode.com/problems/merge-k-sorted-lists/', day: 3, star: true },
      { id: 'fw12p21', name: 'Minimum Interval to Include Each Query', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/', day: 3 },
    ],
    mocks: [
      { id: 'fw12m1', name: 'Mock: Merge Intervals' },
      { id: 'fw12m2', name: 'Mock: N-Queens' },
    ],
  },
  {
    num: 13,
    title: 'Prefix Sum + Difference Array',
    doc: '/docs/DSA-Foundations/week-13-prefix-sum-difference-array',
    problems: [
      { id: 'fw13p1', name: 'Range Sum Query - Immutable', diff: 'Easy', lc: 'https://leetcode.com/problems/range-sum-query-immutable/', day: 1, star: true },
      { id: 'fw13p2', name: 'Find Pivot Index', diff: 'Easy', lc: 'https://leetcode.com/problems/find-pivot-index/', day: 1, star: true },
      { id: 'fw13p3', name: 'Running Sum of 1d Array', diff: 'Easy', lc: 'https://leetcode.com/problems/running-sum-of-1d-array/', day: 1 },
      { id: 'fw13p4', name: 'Subarray Sum Equals K', diff: 'Medium', lc: 'https://leetcode.com/problems/subarray-sum-equals-k/', day: 1, star: true },
      { id: 'fw13p5', name: 'Continuous Subarray Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/continuous-subarray-sum/', day: 1 },
      { id: 'fw13p6', name: 'Product of Array Except Self', diff: 'Medium', lc: 'https://leetcode.com/problems/product-of-array-except-self/', day: 1, star: true },
      { id: 'fw13p7', name: 'Range Sum Query 2D - Immutable', diff: 'Medium', lc: 'https://leetcode.com/problems/range-sum-query-2d-immutable/', day: 1, star: true },
      { id: 'fw13p8', name: 'Corporate Flight Bookings', diff: 'Medium', lc: 'https://leetcode.com/problems/corporate-flight-bookings/', day: 2, star: true },
      { id: 'fw13p9', name: 'Car Pooling', diff: 'Medium', lc: 'https://leetcode.com/problems/car-pooling/', day: 2, star: true },
      { id: 'fw13p10', name: 'Subarray Sums Divisible by K', diff: 'Medium', lc: 'https://leetcode.com/problems/subarray-sums-divisible-by-k/', day: 2 },
      { id: 'fw13p11', name: 'Contiguous Array', diff: 'Medium', lc: 'https://leetcode.com/problems/contiguous-array/', day: 2, star: true },
      { id: 'fw13p12', name: 'Matrix Block Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/matrix-block-sum/', day: 2 },
      { id: 'fw13p13', name: 'Count Number of Nice Subarrays', diff: 'Medium', lc: 'https://leetcode.com/problems/count-number-of-nice-subarrays/', day: 2 },
      { id: 'fw13p14', name: 'Minimum Penalty for a Shop', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-penalty-for-a-shop/', day: 2 },
      { id: 'fw13p15', name: 'Make Sum Divisible by P', diff: 'Medium', lc: 'https://leetcode.com/problems/make-sum-divisible-by-p/', day: 3 },
      { id: 'fw13p16', name: 'Range Addition', diff: 'Medium', lc: 'https://leetcode.com/problems/range-addition/', day: 3 },
      { id: 'fw13p17', name: 'Count of Range Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/count-of-range-sum/', day: 3, star: true },
      { id: 'fw13p18', name: 'Subarrays with K Different Integers', diff: 'Hard', lc: 'https://leetcode.com/problems/subarrays-with-k-different-integers/', day: 3, star: true },
      { id: 'fw13p19', name: 'Number of Submatrices That Sum to Target', diff: 'Hard', lc: 'https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/', day: 3 },
      { id: 'fw13p20', name: 'Max Sum of 3 Non-Overlapping Subarrays', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays/', day: 3 },
      { id: 'fw13p21', name: 'Stamping the Grid', diff: 'Hard', lc: 'https://leetcode.com/problems/stamping-the-grid/', day: 3 },
    ],
    mocks: [
      { id: 'fw13m1', name: 'Mock: Subarray Sum Equals K' },
      { id: 'fw13m2', name: 'Mock: Corporate Flight Bookings' },
    ],
  },
  {
    num: 14,
    title: 'Bit Manipulation',
    doc: '/docs/DSA-Foundations/week-14-bit-manipulation',
    problems: [
      { id: 'fw14p1', name: 'Single Number', diff: 'Easy', lc: 'https://leetcode.com/problems/single-number/', day: 1, star: true },
      { id: 'fw14p2', name: 'Number of 1 Bits', diff: 'Easy', lc: 'https://leetcode.com/problems/number-of-1-bits/', day: 1, star: true },
      { id: 'fw14p3', name: 'Counting Bits', diff: 'Easy', lc: 'https://leetcode.com/problems/counting-bits/', day: 1 },
      { id: 'fw14p4', name: 'Reverse Bits', diff: 'Easy', lc: 'https://leetcode.com/problems/reverse-bits/', day: 1 },
      { id: 'fw14p5', name: 'Missing Number', diff: 'Easy', lc: 'https://leetcode.com/problems/missing-number/', day: 1, star: true },
      { id: 'fw14p6', name: 'Power of Two', diff: 'Easy', lc: 'https://leetcode.com/problems/power-of-two/', day: 1 },
      { id: 'fw14p7', name: 'Hamming Distance', diff: 'Easy', lc: 'https://leetcode.com/problems/hamming-distance/', day: 1 },
      { id: 'fw14p8', name: 'Single Number II', diff: 'Medium', lc: 'https://leetcode.com/problems/single-number-ii/', day: 2, star: true },
      { id: 'fw14p9', name: 'Single Number III', diff: 'Medium', lc: 'https://leetcode.com/problems/single-number-iii/', day: 2 },
      { id: 'fw14p10', name: 'Sum of Two Integers', diff: 'Medium', lc: 'https://leetcode.com/problems/sum-of-two-integers/', day: 2, star: true },
      { id: 'fw14p11', name: 'Bitwise AND of Numbers Range', diff: 'Medium', lc: 'https://leetcode.com/problems/bitwise-and-of-numbers-range/', day: 2 },
      { id: 'fw14p12', name: 'Subsets (Bitmask)', diff: 'Medium', lc: 'https://leetcode.com/problems/subsets/', day: 2, star: true },
      { id: 'fw14p13', name: 'Maximum XOR of Two Numbers', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', day: 2 },
      { id: 'fw14p14', name: 'Total Hamming Distance', diff: 'Medium', lc: 'https://leetcode.com/problems/total-hamming-distance/', day: 2 },
      { id: 'fw14p15', name: 'Decode XORed Permutation', diff: 'Medium', lc: 'https://leetcode.com/problems/decode-xored-permutation/', day: 3 },
      { id: 'fw14p16', name: 'Find the Duplicate Number', diff: 'Medium', lc: 'https://leetcode.com/problems/find-the-duplicate-number/', day: 3, star: true },
      { id: 'fw14p17', name: 'UTF-8 Validation', diff: 'Medium', lc: 'https://leetcode.com/problems/utf-8-validation/', day: 3 },
      { id: 'fw14p18', name: 'Maximum Product of Word Lengths', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-product-of-word-lengths/', day: 3 },
      { id: 'fw14p19', name: 'Minimum Flips to Make a OR b Equal to c', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/', day: 3 },
      { id: 'fw14p20', name: 'XOR Queries of a Subarray', diff: 'Medium', lc: 'https://leetcode.com/problems/xor-queries-of-a-subarray/', day: 3 },
      { id: 'fw14p21', name: 'Concatenation of Consecutive Binary Numbers', diff: 'Medium', lc: 'https://leetcode.com/problems/concatenation-of-consecutive-binary-numbers/', day: 3 },
    ],
    mocks: [
      { id: 'fw14m1', name: 'Mock: Single Number' },
      { id: 'fw14m2', name: 'Mock: Sum of Two Integers' },
    ],
  },
  {
    num: 15,
    title: 'Math + Geometry',
    doc: '/docs/DSA-Foundations/week-15-math-geometry',
    problems: [
      { id: 'fw15p1', name: 'Fizz Buzz', diff: 'Easy', lc: 'https://leetcode.com/problems/fizz-buzz/', day: 1 },
      { id: 'fw15p2', name: 'Count Primes', diff: 'Medium', lc: 'https://leetcode.com/problems/count-primes/', day: 1, star: true },
      { id: 'fw15p3', name: 'Power of Three', diff: 'Easy', lc: 'https://leetcode.com/problems/power-of-three/', day: 1 },
      { id: 'fw15p4', name: 'Happy Number', diff: 'Easy', lc: 'https://leetcode.com/problems/happy-number/', day: 1, star: true },
      { id: 'fw15p5', name: 'Plus One', diff: 'Easy', lc: 'https://leetcode.com/problems/plus-one/', day: 1 },
      { id: 'fw15p6', name: 'Factorial Trailing Zeroes', diff: 'Medium', lc: 'https://leetcode.com/problems/factorial-trailing-zeroes/', day: 1, star: true },
      { id: 'fw15p7', name: 'Excel Sheet Column Number', diff: 'Easy', lc: 'https://leetcode.com/problems/excel-sheet-column-number/', day: 1 },
      { id: 'fw15p8', name: 'Rotate Image', diff: 'Medium', lc: 'https://leetcode.com/problems/rotate-image/', day: 2, star: true },
      { id: 'fw15p9', name: 'Spiral Matrix', diff: 'Medium', lc: 'https://leetcode.com/problems/spiral-matrix/', day: 2, star: true },
      { id: 'fw15p10', name: 'Set Matrix Zeroes', diff: 'Medium', lc: 'https://leetcode.com/problems/set-matrix-zeroes/', day: 2, star: true },
      { id: 'fw15p11', name: 'GCD of Strings', diff: 'Easy', lc: 'https://leetcode.com/problems/greatest-common-divisor-of-strings/', day: 2 },
      { id: 'fw15p12', name: 'Ugly Number II', diff: 'Medium', lc: 'https://leetcode.com/problems/ugly-number-ii/', day: 2, star: true },
      { id: 'fw15p13', name: 'Multiply Strings', diff: 'Medium', lc: 'https://leetcode.com/problems/multiply-strings/', day: 2 },
      { id: 'fw15p14', name: 'Next Permutation', diff: 'Medium', lc: 'https://leetcode.com/problems/next-permutation/', day: 2, star: true },
      { id: 'fw15p15', name: 'Spiral Matrix II', diff: 'Medium', lc: 'https://leetcode.com/problems/spiral-matrix-ii/', day: 3 },
      { id: 'fw15p16', name: 'Max Points on a Line', diff: 'Hard', lc: 'https://leetcode.com/problems/max-points-on-a-line/', day: 3, star: true },
      { id: 'fw15p17', name: 'Pow(x, n)', diff: 'Medium', lc: 'https://leetcode.com/problems/powx-n/', day: 3, star: true },
      { id: 'fw15p18', name: 'Detect Squares', diff: 'Medium', lc: 'https://leetcode.com/problems/detect-squares/', day: 3 },
      { id: 'fw15p19', name: 'Super Pow', diff: 'Medium', lc: 'https://leetcode.com/problems/super-pow/', day: 3 },
      { id: 'fw15p20', name: 'Robot Bounded In Circle', diff: 'Medium', lc: 'https://leetcode.com/problems/robot-bounded-in-circle/', day: 3 },
      { id: 'fw15p21', name: 'Integer to English Words', diff: 'Hard', lc: 'https://leetcode.com/problems/integer-to-english-words/', day: 3 },
    ],
    mocks: [
      { id: 'fw15m1', name: 'Mock: Rotate Image' },
      { id: 'fw15m2', name: 'Mock: Spiral Matrix' },
    ],
  },
  {
    num: 16,
    title: 'Design Problems',
    doc: '/docs/DSA-Foundations/week-16-design-problems',
    problems: [
      { id: 'fw16p1', name: 'Min Stack', diff: 'Medium', lc: 'https://leetcode.com/problems/min-stack/', day: 1, star: true },
      { id: 'fw16p2', name: 'LRU Cache', diff: 'Medium', lc: 'https://leetcode.com/problems/lru-cache/', day: 1, star: true },
      { id: 'fw16p3', name: 'Implement Trie', diff: 'Medium', lc: 'https://leetcode.com/problems/implement-trie-prefix-tree/', day: 1, star: true },
      { id: 'fw16p4', name: 'Design HashMap', diff: 'Easy', lc: 'https://leetcode.com/problems/design-hashmap/', day: 1 },
      { id: 'fw16p5', name: 'Design HashSet', diff: 'Easy', lc: 'https://leetcode.com/problems/design-hashset/', day: 1 },
      { id: 'fw16p6', name: 'Implement Queue using Stacks', diff: 'Easy', lc: 'https://leetcode.com/problems/implement-queue-using-stacks/', day: 1 },
      { id: 'fw16p7', name: 'Design Linked List', diff: 'Medium', lc: 'https://leetcode.com/problems/design-linked-list/', day: 1 },
      { id: 'fw16p8', name: 'LFU Cache', diff: 'Hard', lc: 'https://leetcode.com/problems/lfu-cache/', day: 2, star: true },
      { id: 'fw16p9', name: 'Insert Delete GetRandom O(1)', diff: 'Medium', lc: 'https://leetcode.com/problems/insert-delete-getrandom-o1/', day: 2, star: true },
      { id: 'fw16p10', name: 'Design Add and Search Words', diff: 'Medium', lc: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', day: 2, star: true },
      { id: 'fw16p11', name: 'Serialize and Deserialize Binary Tree', diff: 'Hard', lc: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', day: 2, star: true },
      { id: 'fw16p12', name: 'Design Twitter', diff: 'Medium', lc: 'https://leetcode.com/problems/design-twitter/', day: 2 },
      { id: 'fw16p13', name: 'Flatten Nested List Iterator', diff: 'Medium', lc: 'https://leetcode.com/problems/flatten-nested-list-iterator/', day: 2, star: true },
      { id: 'fw16p14', name: 'BST Iterator', diff: 'Medium', lc: 'https://leetcode.com/problems/binary-search-tree-iterator/', day: 2 },
      { id: 'fw16p15', name: 'Peeking Iterator', diff: 'Medium', lc: 'https://leetcode.com/problems/peeking-iterator/', day: 3 },
      { id: 'fw16p16', name: 'Design Circular Queue', diff: 'Medium', lc: 'https://leetcode.com/problems/design-circular-queue/', day: 3 },
      { id: 'fw16p17', name: 'Design Browser History', diff: 'Medium', lc: 'https://leetcode.com/problems/design-browser-history/', day: 3 },
      { id: 'fw16p18', name: 'Time Based Key-Value Store', diff: 'Medium', lc: 'https://leetcode.com/problems/time-based-key-value-store/', day: 3, star: true },
      { id: 'fw16p19', name: 'Snapshot Array', diff: 'Medium', lc: 'https://leetcode.com/problems/snapshot-array/', day: 3 },
      { id: 'fw16p20', name: 'Maximum Frequency Stack', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-frequency-stack/', day: 3, star: true },
      { id: 'fw16p21', name: 'Design In-Memory File System', diff: 'Hard', lc: 'https://leetcode.com/problems/design-in-memory-file-system/', day: 3 },
    ],
    mocks: [
      { id: 'fw16m1', name: 'Mock: LRU Cache' },
      { id: 'fw16m2', name: 'Mock: LFU Cache' },
    ],
  },
  {
    num: 17,
    title: 'Advanced DP',
    doc: '/docs/DSA-Foundations/week-17-advanced-dp',
    problems: [
      { id: 'fw17p1', name: 'House Robber III', diff: 'Medium', lc: 'https://leetcode.com/problems/house-robber-iii/', day: 1, star: true },
      { id: 'fw17p2', name: 'Best Time Buy Sell Stock with Cooldown', diff: 'Medium', lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', day: 1, star: true },
      { id: 'fw17p3', name: 'Best Time Buy Sell Stock with Fee', diff: 'Medium', lc: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/', day: 1 },
      { id: 'fw17p4', name: 'Min Cost Climbing Stairs', diff: 'Easy', lc: 'https://leetcode.com/problems/min-cost-climbing-stairs/', day: 1 },
      { id: 'fw17p5', name: 'Delete and Earn', diff: 'Medium', lc: 'https://leetcode.com/problems/delete-and-earn/', day: 1, star: true },
      { id: 'fw17p6', name: 'Ones and Zeroes', diff: 'Medium', lc: 'https://leetcode.com/problems/ones-and-zeroes/', day: 1, star: true },
      { id: 'fw17p7', name: 'Last Stone Weight II', diff: 'Medium', lc: 'https://leetcode.com/problems/last-stone-weight-ii/', day: 1 },
      { id: 'fw17p8', name: 'Partition Equal Subset Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/partition-equal-subset-sum/', day: 2, star: true },
      { id: 'fw17p9', name: 'Target Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/target-sum/', day: 2, star: true },
      { id: 'fw17p10', name: 'Coin Change II', diff: 'Medium', lc: 'https://leetcode.com/problems/coin-change-ii/', day: 2, star: true },
      { id: 'fw17p11', name: 'Combination Sum IV', diff: 'Medium', lc: 'https://leetcode.com/problems/combination-sum-iv/', day: 2 },
      { id: 'fw17p12', name: 'Min Cost for Tickets', diff: 'Medium', lc: 'https://leetcode.com/problems/minimum-cost-for-tickets/', day: 2, star: true },
      { id: 'fw17p13', name: 'Integer Break', diff: 'Medium', lc: 'https://leetcode.com/problems/integer-break/', day: 2 },
      { id: 'fw17p14', name: 'Interleaving String', diff: 'Medium', lc: 'https://leetcode.com/problems/interleaving-string/', day: 2 },
      { id: 'fw17p15', name: 'Max Profit in Job Scheduling', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', day: 3, star: true },
      { id: 'fw17p16', name: 'Burst Balloons', diff: 'Hard', lc: 'https://leetcode.com/problems/burst-balloons/', day: 3, star: true },
      { id: 'fw17p17', name: 'Palindrome Partitioning II', diff: 'Hard', lc: 'https://leetcode.com/problems/palindrome-partitioning-ii/', day: 3 },
      { id: 'fw17p18', name: 'Minimum Cost to Cut a Stick', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/', day: 3 },
      { id: 'fw17p19', name: 'Unique BSTs', diff: 'Medium', lc: 'https://leetcode.com/problems/unique-binary-search-trees/', day: 3, star: true },
      { id: 'fw17p20', name: 'Perfect Squares', diff: 'Medium', lc: 'https://leetcode.com/problems/perfect-squares/', day: 3 },
      { id: 'fw17p21', name: 'Cherry Pickup II', diff: 'Hard', lc: 'https://leetcode.com/problems/cherry-pickup-ii/', day: 3 },
    ],
    mocks: [
      { id: 'fw17m1', name: 'Mock: Partition Equal Subset Sum' },
      { id: 'fw17m2', name: 'Mock: Burst Balloons' },
    ],
  },
  {
    num: 18,
    title: 'String Algorithms',
    doc: '/docs/DSA-Foundations/week-18-string-algorithms',
    problems: [
      { id: 'fw18p1', name: 'Implement strStr (KMP)', diff: 'Easy', lc: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', day: 1, star: true },
      { id: 'fw18p2', name: 'Repeated Substring Pattern', diff: 'Easy', lc: 'https://leetcode.com/problems/repeated-substring-pattern/', day: 1 },
      { id: 'fw18p3', name: 'Longest Common Prefix', diff: 'Easy', lc: 'https://leetcode.com/problems/longest-common-prefix/', day: 1 },
      { id: 'fw18p4', name: 'Longest Palindromic Substring', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-palindromic-substring/', day: 1, star: true },
      { id: 'fw18p5', name: 'Palindromic Substrings', diff: 'Medium', lc: 'https://leetcode.com/problems/palindromic-substrings/', day: 1, star: true },
      { id: 'fw18p6', name: 'Word Break', diff: 'Medium', lc: 'https://leetcode.com/problems/word-break/', day: 1, star: true },
      { id: 'fw18p7', name: 'Word Break II', diff: 'Hard', lc: 'https://leetcode.com/problems/word-break-ii/', day: 1 },
      { id: 'fw18p8', name: 'Word Search II', diff: 'Hard', lc: 'https://leetcode.com/problems/word-search-ii/', day: 2, star: true },
      { id: 'fw18p9', name: 'Replace Words', diff: 'Medium', lc: 'https://leetcode.com/problems/replace-words/', day: 2 },
      { id: 'fw18p10', name: 'Longest Happy Prefix', diff: 'Hard', lc: 'https://leetcode.com/problems/longest-happy-prefix/', day: 2, star: true },
      { id: 'fw18p11', name: 'Repeated DNA Sequences', diff: 'Medium', lc: 'https://leetcode.com/problems/repeated-dna-sequences/', day: 2 },
      { id: 'fw18p12', name: 'Shortest Palindrome', diff: 'Hard', lc: 'https://leetcode.com/problems/shortest-palindrome/', day: 2, star: true },
      { id: 'fw18p13', name: 'Concatenated Words', diff: 'Hard', lc: 'https://leetcode.com/problems/concatenated-words/', day: 2 },
      { id: 'fw18p14', name: 'Map Sum Pairs', diff: 'Medium', lc: 'https://leetcode.com/problems/map-sum-pairs/', day: 2 },
      { id: 'fw18p15', name: 'Longest Duplicate Substring', diff: 'Hard', lc: 'https://leetcode.com/problems/longest-duplicate-substring/', day: 3, star: true },
      { id: 'fw18p16', name: 'Encode and Decode Strings', diff: 'Medium', lc: 'https://leetcode.com/problems/encode-and-decode-strings/', day: 3 },
      { id: 'fw18p17', name: 'Distinct Subsequences', diff: 'Hard', lc: 'https://leetcode.com/problems/distinct-subsequences/', day: 3 },
      { id: 'fw18p18', name: 'Count Different Palindromic Subsequences', diff: 'Hard', lc: 'https://leetcode.com/problems/count-different-palindromic-subsequences/', day: 3 },
      { id: 'fw18p19', name: 'Palindrome Pairs', diff: 'Hard', lc: 'https://leetcode.com/problems/palindrome-pairs/', day: 3, star: true },
      { id: 'fw18p20', name: 'Sum of Prefix Scores', diff: 'Hard', lc: 'https://leetcode.com/problems/sum-of-prefix-scores-of-strings/', day: 3 },
      { id: 'fw18p21', name: 'Minimum Window Substring', diff: 'Hard', lc: 'https://leetcode.com/problems/minimum-window-substring/', day: 3, star: true },
    ],
    mocks: [
      { id: 'fw18m1', name: 'Mock: Word Break' },
      { id: 'fw18m2', name: 'Mock: Shortest Palindrome' },
    ],
  },
  {
    num: 19,
    title: 'Monotonic Stack + Advanced Sliding Window',
    doc: '/docs/DSA-Foundations/week-19-monotonic-stack-advanced-window',
    problems: [
      { id: 'fw19p1', name: 'Next Greater Element I', diff: 'Easy', lc: 'https://leetcode.com/problems/next-greater-element-i/', day: 1, star: true },
      { id: 'fw19p2', name: 'Next Greater Element II', diff: 'Medium', lc: 'https://leetcode.com/problems/next-greater-element-ii/', day: 1 },
      { id: 'fw19p3', name: 'Daily Temperatures', diff: 'Medium', lc: 'https://leetcode.com/problems/daily-temperatures/', day: 1, star: true },
      { id: 'fw19p4', name: 'Online Stock Span', diff: 'Medium', lc: 'https://leetcode.com/problems/online-stock-span/', day: 1 },
      { id: 'fw19p5', name: 'Remove K Digits', diff: 'Medium', lc: 'https://leetcode.com/problems/remove-k-digits/', day: 1, star: true },
      { id: 'fw19p6', name: 'Sum of Subarray Minimums', diff: 'Medium', lc: 'https://leetcode.com/problems/sum-of-subarray-minimums/', day: 1, star: true },
      { id: 'fw19p7', name: '132 Pattern', diff: 'Medium', lc: 'https://leetcode.com/problems/132-pattern/', day: 1 },
      { id: 'fw19p8', name: 'Largest Rectangle in Histogram', diff: 'Hard', lc: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', day: 2, star: true },
      { id: 'fw19p9', name: 'Maximal Rectangle', diff: 'Hard', lc: 'https://leetcode.com/problems/maximal-rectangle/', day: 2, star: true },
      { id: 'fw19p10', name: 'Trapping Rain Water', diff: 'Hard', lc: 'https://leetcode.com/problems/trapping-rain-water/', day: 2, star: true },
      { id: 'fw19p11', name: 'Sliding Window Maximum', diff: 'Hard', lc: 'https://leetcode.com/problems/sliding-window-maximum/', day: 2, star: true },
      { id: 'fw19p12', name: 'Longest Substring with At Most K Distinct', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/', day: 2 },
      { id: 'fw19p13', name: 'Fruit Into Baskets', diff: 'Medium', lc: 'https://leetcode.com/problems/fruit-into-baskets/', day: 2 },
      { id: 'fw19p14', name: 'Maximum Width Ramp', diff: 'Medium', lc: 'https://leetcode.com/problems/maximum-width-ramp/', day: 2 },
      { id: 'fw19p15', name: 'Shortest Subarray with Sum at Least K', diff: 'Hard', lc: 'https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/', day: 3, star: true },
      { id: 'fw19p16', name: 'Sum of Subarray Ranges', diff: 'Medium', lc: 'https://leetcode.com/problems/sum-of-subarray-ranges/', day: 3 },
      { id: 'fw19p17', name: 'Steps to Make Array Non-decreasing', diff: 'Medium', lc: 'https://leetcode.com/problems/steps-to-make-array-non-decreasing/', day: 3 },
      { id: 'fw19p18', name: 'Number of Visible People in Queue', diff: 'Hard', lc: 'https://leetcode.com/problems/number-of-visible-people-in-a-queue/', day: 3 },
      { id: 'fw19p19', name: 'Constrained Subsequence Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/constrained-subsequence-sum/', day: 3 },
      { id: 'fw19p20', name: 'Maximum Score of Good Subarray', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-score-of-a-good-subarray/', day: 3 },
      { id: 'fw19p21', name: 'Longest Bounded-Difference Subarray', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/', day: 3 },
    ],
    mocks: [
      { id: 'fw19m1', name: 'Mock: Largest Rectangle in Histogram' },
      { id: 'fw19m2', name: 'Mock: Trapping Rain Water' },
    ],
  },
  {
    num: 20,
    title: 'Final Review + Mock Interviews',
    doc: '/docs/DSA-Foundations/week-20-final-review',
    problems: [
      { id: 'fw20p1', name: 'Two Sum', diff: 'Easy', lc: 'https://leetcode.com/problems/two-sum/', day: 1, star: true },
      { id: 'fw20p2', name: '3Sum', diff: 'Medium', lc: 'https://leetcode.com/problems/3sum/', day: 1, star: true },
      { id: 'fw20p3', name: 'Merge Intervals', diff: 'Medium', lc: 'https://leetcode.com/problems/merge-intervals/', day: 1, star: true },
      { id: 'fw20p4', name: 'Longest Increasing Subsequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-increasing-subsequence/', day: 1, star: true },
      { id: 'fw20p5', name: 'Course Schedule', diff: 'Medium', lc: 'https://leetcode.com/problems/course-schedule/', day: 1, star: true },
      { id: 'fw20p6', name: 'Binary Tree Maximum Path Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', day: 1, star: true },
      { id: 'fw20p7', name: 'Word Ladder', diff: 'Hard', lc: 'https://leetcode.com/problems/word-ladder/', day: 1, star: true },
      { id: 'fw20p8', name: 'LRU Cache', diff: 'Medium', lc: 'https://leetcode.com/problems/lru-cache/', day: 2, star: true },
      { id: 'fw20p9', name: 'Median of Two Sorted Arrays', diff: 'Hard', lc: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', day: 2, star: true },
      { id: 'fw20p10', name: 'Serialize and Deserialize Binary Tree', diff: 'Hard', lc: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', day: 2, star: true },
      { id: 'fw20p11', name: 'Trapping Rain Water', diff: 'Hard', lc: 'https://leetcode.com/problems/trapping-rain-water/', day: 2, star: true },
      { id: 'fw20p12', name: 'Edit Distance', diff: 'Medium', lc: 'https://leetcode.com/problems/edit-distance/', day: 2, star: true },
      { id: 'fw20p13', name: 'Longest Common Subsequence', diff: 'Medium', lc: 'https://leetcode.com/problems/longest-common-subsequence/', day: 2, star: true },
      { id: 'fw20p14', name: 'Max Profit in Job Scheduling', diff: 'Hard', lc: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', day: 2, star: true },
      { id: 'fw20p15', name: 'Merge K Sorted Lists', diff: 'Hard', lc: 'https://leetcode.com/problems/merge-k-sorted-lists/', day: 3, star: true },
      { id: 'fw20p16', name: 'Find Median from Data Stream', diff: 'Hard', lc: 'https://leetcode.com/problems/find-median-from-data-stream/', day: 3, star: true },
      { id: 'fw20p17', name: 'Alien Dictionary', diff: 'Hard', lc: 'https://leetcode.com/problems/alien-dictionary/', day: 3, star: true },
      { id: 'fw20p18', name: 'N-Queens', diff: 'Hard', lc: 'https://leetcode.com/problems/n-queens/', day: 3, star: true },
      { id: 'fw20p19', name: 'Burst Balloons', diff: 'Hard', lc: 'https://leetcode.com/problems/burst-balloons/', day: 3, star: true },
      { id: 'fw20p20', name: 'Split Array Largest Sum', diff: 'Hard', lc: 'https://leetcode.com/problems/split-array-largest-sum/', day: 3, star: true },
      { id: 'fw20p21', name: 'Reverse Nodes in k-Group', diff: 'Hard', lc: 'https://leetcode.com/problems/reverse-nodes-in-k-group/', day: 3, star: true },
    ],
    mocks: [
      { id: 'fw20m1', name: 'Final Mock 1: Arrays + Trees' },
      { id: 'fw20m2', name: 'Final Mock 2: Graphs + DP' },
      { id: 'fw20m3', name: 'Final Mock 3: Design + Strings' },
      { id: 'fw20m4', name: 'Final Mock 4: Mixed Hard' },
    ],
  },
];
