// ─────────────────────────────────────────────────────────────────────────────
// Interview Checklist — Comprehensive Topic Data
// ─────────────────────────────────────────────────────────────────────────────

// Each category has: id, title, color (for the phase accent bar)
// Each section has: id, title
// Each item has: id, name, optional note, optional resource

export const CATEGORIES = [
  { id: 'behavioural', label: 'Behavioural', color: '#00f0ff' },
  { id: 'experience', label: 'Experience', color: '#a855f7' },
  { id: 'system-design', label: 'System Design', color: '#f472b6' },
  { id: 'microservices', label: 'Microservices', color: '#34d399' },
  { id: 'databases', label: 'Databases', color: '#f59e0b' },
  { id: 'cs-fundamentals', label: 'CS Fundamentals', color: '#00f0ff' },
  { id: 'math', label: 'Math & Probability', color: '#ef4444' },
];

export const TOPICS_DATA = {

  // ══════════════════════════════════════════════════════════════════════════════
  // 1. BEHAVIOURAL / LEADERSHIP
  // ══════════════════════════════════════════════════════════════════════════════
  behavioural: {
    sections: [
      {
        id: 'b-core-values',
        title: 'Core Values & Principles',
        items: [
          { id: 'b1', name: 'Define your top 5 personal values' },
          { id: 'b2', name: 'Explain how your values guided a difficult decision', note: 'Be specific — name the tension, the options, and what you chose' },
          { id: 'b3', name: 'Describe a time you chose integrity over convenience', note: 'What was at stake? What would have been easier?' },
          { id: 'b4', name: 'Share an example of radical ownership — taking responsibility for a failure', note: 'Avoid blaming the team, the manager, or external factors' },
          { id: 'b5', name: 'Explain how you balance speed vs. quality', note: 'Give a concrete example where you made a trade-off call' },
          { id: 'b6', name: 'Describe your definition of engineering excellence', note: 'What standards do you hold yourself and your team to?' },
          { id: 'b7', name: 'Explain how you handle ambiguity', note: 'Give an example of vague requirements you navigated' },
          { id: 'b8', name: 'Share a time you advocated for something you believed in despite pushback' },
        ],
      },
      {
        id: 'b-star-framework',
        title: 'STAR Method — Story Bank',
        items: [
          { id: 'b9', name: 'Prepare a STAR story for: Accomplishment you are most proud of', note: 'Focus on YOUR specific contribution, not the team generically' },
          { id: 'b10', name: 'Prepare a STAR story for: A time you failed and what you learned' },
          { id: 'b11', name: 'Prepare a STAR story for: A conflict with a coworker and how you resolved it' },
          { id: 'b12', name: 'Prepare a STAR story for: A time you had to deliver under tight deadline' },
          { id: 'b13', name: 'Prepare a STAR story for: A technical challenge you solved creatively' },
          { id: 'b14', name: 'Prepare a STAR story for: A time you improved a process or eliminated waste' },
          { id: 'b15', name: 'Prepare a STAR story for: Leading without formal authority' },
          { id: 'b16', name: 'Prepare a STAR story for: Disagreeing with your manager and winning' },
          { id: 'b17', name: 'Prepare a STAR story for: Mentoring or teaching someone else' },
          { id: 'b18', name: 'Prepare a STAR story for: Making a decision with incomplete information' },
          { id: 'b19', name: 'Prepare a STAR story for: Receiving critical feedback and how you responded' },
          { id: 'b20', name: 'Prepare a STAR story for: Working with a difficult stakeholder' },
        ],
      },
      {
        id: 'b-conflict',
        title: 'Conflict Resolution',
        items: [
          { id: 'b21', name: 'Describe your approach to resolving technical disagreements with peers' },
          { id: 'b22', name: 'Explain how you handle it when someone on your team is underperforming', note: 'What steps do you take before escalating?' },
          { id: 'b23', name: 'Share a time you had to deliver hard feedback to a direct report' },
          { id: 'b24', name: 'Describe a time you were in a deadlock and how you broke it' },
          { id: 'b25', name: 'Explain how you handle it when two team members cannot work together' },
          { id: 'b26', name: 'Share an experience navigating a disagreement with a senior leader' },
          { id: 'b27', name: 'Describe how you balance empathy with accountability' },
        ],
      },
      {
        id: 'b-leadership',
        title: 'Leadership & Influence',
        items: [
          { id: 'b28', name: 'Describe your approach to delegating work', note: 'How do you decide what to delegate vs. do yourself?' },
          { id: 'b29', name: 'Explain how you onboard and ramp up a new team member' },
          { id: 'b30', name: 'Share how you have grown a junior engineer into a strong performer' },
          { id: 'b31', name: 'Describe a time you had to motivate a demotivated team' },
          { id: 'b32', name: 'Explain how you make decisions when the team is split on direction' },
          { id: 'b33', name: 'Share how you balance contributing code vs. enabling others' },
          { id: 'b34', name: 'Describe your approach to running effective 1-on-1s' },
          { id: 'b35', name: 'Explain how you set and communicate technical vision to a team' },
          { id: 'b36', name: 'Share a time you had to drive adoption of a tool or practice change' },
          { id: 'b37', name: 'Describe how you handle being in the middle between management and ICs' },
        ],
      },
      {
        id: 'b-communication',
        title: 'Communication',
        items: [
          { id: 'b38', name: 'Explain how you adapt your communication for technical vs. non-technical audiences' },
          { id: 'b39', name: 'Describe how you write effective engineering documents', note: 'ADRs, design docs, RFCs — what makes them good?' },
          { id: 'b40', name: 'Share how you run a design review or architecture discussion' },
          { id: 'b41', name: 'Explain how you communicate bad news (delays, outages, failures) upward' },
          { id: 'b42', name: 'Describe how you ensure alignment across multiple teams' },
          { id: 'b43', name: 'Share your approach to handling Q&A in a large presentation' },
          { id: 'b44', name: 'Explain how you make complex technical concepts clear in an interview setting' },
        ],
      },
      {
        id: 'b-growth',
        title: 'Growth & Self-Awareness',
        items: [
          { id: 'b45', name: 'What are the 2-3 areas you are actively working to improve?' },
          { id: 'b46', name: 'Share the best piece of career advice you have received' },
          { id: 'b47', name: 'Describe a skill you had to learn from scratch to succeed in a role' },
          { id: 'b48', name: 'Where do you see yourself in 3-5 years?', note: 'Be honest and specific — not generic "I want to grow"' },
          { id: 'b49', name: 'Share a time you主动 sought feedback and what you did with it' },
          { id: 'b50', name: 'Describe your biggest professional mistake and how you recovered' },
          { id: 'b51', name: 'What does your ideal engineering culture look like?' },
          { id: 'b52', name: 'How do you stay current with technology trends without burning out?' },
        ],
      },
      {
        id: 'b-pressure',
        title: 'Pressure & Prioritization',
        items: [
          { id: 'b53', name: 'Describe how you prioritize when everything feels urgent' },
          { id: 'b54', name: 'Share how you handle working on multiple projects simultaneously' },
          { id: 'b55', name: 'Explain how you manage stress during a production incident' },
          { id: 'b56', name: 'Describe a time you had to say no to a stakeholder and how you did it' },
          { id: 'b57', name: 'Share how you maintain quality when moving fast' },
          { id: 'b58', name: 'Explain your approach to work-life balance and preventing burnout' },
          { id: 'b59', name: 'Describe a time you had to cut scope mid-sprint and how you managed it' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 2. EXPERIENCE & PROJECT DEEP-DIVE
  // ══════════════════════════════════════════════════════════════════════════════
  experience: {
    sections: [
      {
        id: 'e-project-overview',
        title: 'Project Overview',
        items: [
          { id: 'e1', name: 'Can you describe your current/last project in 2-3 sentences to a non-technical person?' },
          { id: 'e2', name: 'What problem does your system solve? What would break if it went down?' },
          { id: 'e3', name: 'What is the scale of your system? (requests/sec, data volume, users, SLAs)' },
          { id: 'e4', name: 'What was your specific role and ownership area?' },
          { id: 'e5', name: 'What tech stack does your system use and why was it chosen?' },
          { id: 'e6', name: 'How long did it take to build? What were the major milestones?' },
          { id: 'e7', name: 'How many engineers work on this system? How is ownership divided?' },
        ],
      },
      {
        id: 'e-architecture',
        title: 'Architecture Decisions',
        items: [
          { id: 'e8', name: 'Walk through the high-level architecture of a system you designed' },
          { id: 'e9', name: 'Describe a significant architectural trade-off you made and why', note: 'e.g., consistency vs. availability, simplicity vs. flexibility' },
          { id: 'e10', name: 'What alternatives did you consider? Why did you reject them?' },
          { id: 'e11', name: 'If you could redesign your system from scratch, what would you change?' },
          { id: 'e12', name: 'How do you document architecture decisions?', note: 'Be ready to discuss ADRs, design docs, RFCs' },
          { id: 'e13', name: 'Describe how you evaluated build vs. buy vs. open-source for a component' },
          { id: 'e14', name: 'Share a time your initial architecture choice turned out to be wrong' },
          { id: 'e15', name: 'How do you ensure your system can evolve as requirements change?' },
        ],
      },
      {
        id: 'e-impact',
        title: 'Impact & Metrics',
        items: [
          { id: 'e16', name: 'What measurable impact did your work have? (revenue, latency, reliability, user count)' },
          { id: 'e17', name: 'Can you quantify a problem you solved and the before/after state?' },
          { id: 'e18', name: 'What KPIs does your system track? How do they translate to business outcomes?' },
          { id: 'e19', name: 'Describe a project where you had to prove ROI to get approval' },
          { id: 'e20', name: 'Share how you identify what to work on when not given explicit direction' },
          { id: 'e21', name: 'Describe a time you had to convince leadership to invest in technical debt reduction' },
          { id: 'e22', name: 'What is the biggest technical challenge you overcame this year and what was the impact?' },
        ],
      },
      {
        id: 'e-technical-challenges',
        title: 'Technical Challenges',
        items: [
          { id: 'e23', name: 'Describe the hardest technical problem you have solved in the past year' },
          { id: 'e24', name: 'Walk through a debugging session where you tracked down a subtle bug' },
          { id: 'e25', name: 'Share a time you had to optimize a slow system — what was the bottleneck?' },
          { id: 'e26', name: 'Describe a production incident you led the resolution for', note: 'Root cause, timeline, what you fixed, postmortem' },
          { id: 'e27', name: 'Share a time you introduced a breaking change and had to migrate safely' },
          { id: 'e28', name: 'Describe a performance problem that required changing the algorithm or data structure' },
          { id: 'e29', name: 'Share a time you had to debug a distributed systems issue (race conditions, network partitions, etc.)' },
          { id: 'e30', name: 'Describe a time you had to work around a third-party dependency failure' },
          { id: 'e31', name: 'Share a scenario where you had to balance security vs. usability trade-offs' },
        ],
      },
      {
        id: 'e-collaboration',
        title: 'Cross-Team Collaboration',
        items: [
          { id: 'e32', name: 'Describe a time you collaborated with a team on a shared service or API' },
          { id: 'e33', name: 'Share how you handle API versioning when multiple teams depend on you' },
          { id: 'e34', name: 'Describe a project that required coordinating across 3+ teams' },
          { id: 'e35', name: 'Share how you manage dependencies and negotiate delivery timelines with upstream/downstream teams' },
          { id: 'e36', name: 'Describe how you work with product managers to define scope' },
          { id: 'e37', name: 'Share a time you had to influence a team that did not report to you' },
        ],
      },
      {
        id: 'e-career-trajectory',
        title: 'Career & Growth',
        items: [
          { id: 'e38', name: 'Walk me through your career progression and the key transitions' },
          { id: 'e39', name: 'What has been the biggest change in your role from IC to your current level?' },
          { id: 'e40', name: 'Describe the project that stretched you the most professionally' },
          { id: 'e41', name: 'What would your manager say is your biggest strength? Your biggest area for growth?' },
          { id: 'e42', name: 'What is the most ambiguous situation you have navigated? How did you create clarity?' },
          { id: 'e43', name: 'Describe a time you had to ramp up quickly on a new technology or domain' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 3. SYSTEM DESIGN
  // ══════════════════════════════════════════════════════════════════════════════
  'system-design': {
    sections: [
      {
        id: 'sd-fundamentals',
        title: 'Fundamentals & Trade-offs',
        items: [
          { id: 'sd1', name: 'Explain CAP theorem and its implications for distributed systems' },
          { id: 'sd2', name: 'Describe the difference between consistency, availability, and partition tolerance', note: 'When would you prioritize each?' },
          { id: 'sd3', name: 'What is PACELC and how does it extend CAP?' },
          { id: 'sd4', name: 'Explain the fallacies of distributed computing' },
          { id: 'sd5', name: 'Describe horizontal vs. vertical scaling — pros and cons of each' },
          { id: 'sd6', name: 'What is the difference between a proxy, load balancer, and reverse proxy?' },
          { id: 'sd7', name: 'Explain load balancing strategies: Round Robin, Least Connections, IP Hash, Weighted' },
          { id: 'sd8', name: 'What is a circuit breaker pattern? When would you use it?' },
          { id: 'sd9', name: 'Explain bulkhead and retry patterns in distributed systems' },
          { id: 'sd10', name: 'What is a rate limiter? Describe different algorithms (token bucket, leaky bucket, fixed window)' },
          { id: 'sd11', name: 'Describe the leader-follower, multi-leader, and leaderless replication models' },
          { id: 'sd12', name: 'What is eventual consistency vs. strong consistency? When is each acceptable?' },
          { id: 'sd13', name: 'Explain quorum-based replication and the read/write quorum formula' },
          { id: 'sd14', name: 'What is sharding/partitioning? List different partitioning strategies and their trade-offs' },
          { id: 'sd15', name: 'Describe consistent hashing and its benefits over modulo-N hashing' },
          { id: 'sd16', name: 'What is a distributed hash table (DHT)?' },
          { id: 'sd17', name: 'Explain the two generals problem and why consensus is hard' },
          { id: 'sd18', name: 'What is the FLP impossibility result?' },
        ],
      },
      {
        id: 'sd-scalability',
        title: 'Scalability Patterns',
        items: [
          { id: 'sd19', name: 'How would you scale a service from 100 to 10 million users?' },
          { id: 'sd20', name: 'Explain read replicas and when to use them' },
          { id: 'sd21', name: 'What is a write-behind / write-through cache strategy?' },
          { id: 'sd22', name: 'Describe CDN architecture and when you would use one' },
          { id: 'sd23', name: 'What is data federation / scatter-gather pattern?' },
          { id: 'sd24', name: 'Explain database connection pooling and why it matters at scale' },
          { id: 'sd25', name: 'What is database denormalization and when is it appropriate?' },
          { id: 'sd26', name: 'Describe the CQRS (Command Query Responsibility Segregation) pattern' },
          { id: 'sd27', name: 'What is event sourcing and what are its pros and cons?' },
          { id: 'sd28', name: 'Explain change data capture (CDC) and its use cases' },
          { id: 'sd29', name: 'What is the lambda architecture? When is it appropriate over kappa?' },
          { id: 'sd30', name: 'Describe how to handle hot partitions in a sharded database' },
          { id: 'sd31', name: 'What is vertical partitioning vs. horizontal partitioning of data?' },
          { id: 'sd32', name: 'Explain the "scale cube" (X, Y, Z axes of scaling)' },
        ],
      },
      {
        id: 'sd-caching',
        title: 'Caching',
        items: [
          { id: 'sd33', name: 'Describe cache eviction policies: LRU, LFU, FIFO, TTL, Random' },
          { id: 'sd34', name: 'What is cache-aside (lazy loading) vs. write-through vs. write-behind caching?' },
          { id: 'sd35', name: 'Explain cache stampede (thundering herd) problem and solutions', note: 'Locking, jitter, probabilistic early expiration' },
          { id: 'sd36', name: 'What is a distributed cache? Name examples (Redis, Memcached)' },
          { id: 'sd37', name: 'How do you handle cache invalidation?' },
          { id: 'sd38', name: 'What is a bloom filter and what is it used for in caching?' },
          { id: 'sd39', name: 'Describe multi-level caching strategies (L1, L2, L3 caches)' },
          { id: 'sd40', name: 'What is the difference between local cache and shared/distributed cache?' },
          { id: 'sd41', name: 'How would you cache user session data in a distributed system?' },
          { id: 'sd42', name: 'What are the pitfalls of caching immutable data vs. mutable data?' },
        ],
      },
      {
        id: 'sd-messaging',
        title: 'Messaging & Async Communication',
        items: [
          { id: 'sd43', name: 'Explain point-to-point vs. pub/sub messaging models' },
          { id: 'sd44', name: 'What is a message queue? What problems does it solve?' },
          { id: 'sd45', name: 'Describe at-least-once, at-most-once, and exactly-once delivery semantics' },
          { id: 'sd46', name: 'What is a dead letter queue (DLQ) and why is it important?' },
          { id: 'sd47', name: 'Explain message ordering guarantees and how to achieve them' },
          { id: 'sd48', name: 'What is idempotency and why does it matter in message processing?' },
          { id: 'sd49', name: 'Describe how you would design a reliable message processing pipeline' },
          { id: 'sd50', name: 'What is backpressure and how do you handle it in async systems?' },
          { id: 'sd51', name: 'Explain the outbox pattern for reliable event publishing' },
          { id: 'sd52', name: 'What is the saga pattern for distributed transactions?' },
          { id: 'sd53', name: 'Describe event-driven architecture and its benefits/drawbacks' },
          { id: 'sd54', name: 'What is choreography vs. orchestration in saga implementations?' },
        ],
      },
      {
        id: 'sd-storage',
        title: 'Data Storage & Retrieval',
        items: [
          { id: 'sd55', name: 'When would you choose SQL vs. NoSQL? Give specific use case examples' },
          { id: 'sd56', name: 'Describe how a relational database stores data on disk (pages, indexes)' },
          { id: 'sd57', name: 'What is an index? How does a B-tree index work?' },
          { id: 'sd58', name: 'Explain the difference between clustered and non-clustered indexes' },
          { id: 'sd59', name: 'What is a covering index and when would you use it?' },
          { id: 'sd60', name: 'Describe different index types: hash, B-tree, R-tree, GiST, GIN, inverted' },
          { id: 'sd61', name: 'What is write-ahead logging (WAL)? How does it relate to durability?' },
          { id: 'sd62', name: 'Explain ACID properties and how they are implemented in databases' },
          { id: 'sd63', name: 'What is a materialized view? When would you use one?' },
          { id: 'sd64', name: 'Describe columnar storage and when it outperforms row-oriented storage' },
          { id: 'sd65', name: 'What is time-series data storage? Name examples (InfluxDB, TimescaleDB)' },
          { id: 'sd66', name: 'Explain object storage vs. block storage vs. file storage' },
          { id: 'sd67', name: 'What is a data warehouse vs. a data lake? When to use each?' },
          { id: 'sd68', name: 'Describe graph databases and when to use them over relational databases' },
        ],
      },
      {
        id: 'sd-reliability',
        title: 'Reliability & Observability',
        items: [
          { id: 'sd69', name: 'Define SLA, SLO, and SLI. What are examples of each?' },
          { id: 'sd70', name: 'How do you define and measure availability (nines of availability)?' },
          { id: 'sd71', name: 'Describe how you would design a system with 99.99% uptime' },
          { id: 'sd72', name: 'What is a runbook? What should it contain?' },
          { id: 'sd73', name: 'Describe the pillars of observability: metrics, logs, traces' },
          { id: 'sd74', name: 'What is the RED method for measuring service health?' },
          { id: 'sd75', name: 'Explain USE method (Utilization, Saturation, Errors) for performance analysis' },
          { id: 'sd76', name: 'What is distributed tracing? Name tools (Jaeger, Zipkin, OpenTelemetry)' },
          { id: 'sd77', name: 'What is a composite SLI/SLO? Give an example' },
          { id: 'sd78', name: 'Describe error budget budgeting and how it informs engineering decisions' },
          { id: 'sd79', name: 'What is the difference between a postmortem and a retrospective?' },
          { id: 'sd80', name: 'Explain health check patterns: deep checks vs. shallow checks' },
          { id: 'sd81', name: 'What is chaos engineering? Name tools (Chaos Monkey, Gremlin)' },
          { id: 'sd82', name: 'Describe the canary deployment strategy and how you monitor it' },
          { id: 'sd83', name: 'What is a feature flag? How does it support safe deployments?' },
        ],
      },
      {
        id: 'sd-networking',
        title: 'Networking',
        items: [
          { id: 'sd84', name: 'Explain the OSI 7-layer model and what each layer does' },
          { id: 'sd85', name: 'What is the difference between TCP and UDP? When would you use each?' },
          { id: 'sd86', name: 'Describe the 3-way handshake (TCP) and 4-way挥手' },
          { id: 'sd87', name: 'What is HTTP/2 vs. HTTP/1.1 vs. HTTP/3 (QUIC)? Key differences?' },
          { id: 'sd88', name: 'What is TLS 1.3 and how does it improve on TLS 1.2?' },
          { id: 'sd89', name: 'Explain DNS record types: A, AAAA, CNAME, MX, TXT, NS, SOA' },
          { id: 'sd90', name: 'What is round-robin DNS and its limitations?' },
          { id: 'sd91', name: 'Describe Anycast routing and its use cases' },
          { id: 'sd92', name: 'What is a VPC (Virtual Private Cloud)? How does network isolation work?' },
          { id: 'sd93', name: 'Explain subnetting and CIDR notation' },
          { id: 'sd94', name: 'What is a firewall, and the difference between stateful and stateless?' },
          { id: 'sd95', name: 'Describe the purpose of a WAF (Web Application Firewall)' },
          { id: 'sd96', name: 'What is a VPN and how does it work?' },
          { id: 'sd97', name: 'Explain WebSocket and when to use it vs. HTTP long-polling vs. Server-Sent Events' },
          { id: 'sd98', name: 'What is gRPC? How does it compare to REST?' },
          { id: 'sd99', name: 'Describe API versioning strategies (URL path, header, query param)' },
        ],
      },
      {
        id: 'sd-security',
        title: 'Security',
        items: [
          { id: 'sd100', name: 'Explain authentication vs. authorization and name common approaches (OAuth2, SAML, JWT, API keys)' },
          { id: 'sd101', name: 'What is OAuth 2.0? Describe the authorization code flow' },
          { id: 'sd102', name: 'What is OpenID Connect (OIDC) and how does it relate to OAuth2?' },
          { id: 'sd103', name: 'Explain the difference between symmetric and asymmetric encryption' },
          { id: 'sd104', name: 'What is a hash function? Name common ones (SHA-256, bcrypt, Argon2)' },
          { id: 'sd105', name: 'Describe how password hashing should be done properly' },
          { id: 'sd106', name: 'What is salting and why is it important?' },
          { id: 'sd107', name: 'Explain CSRF (Cross-Site Request Forgery) and how to prevent it' },
          { id: 'sd108', name: 'Explain XSS (Cross-Site Scripting) and mitigation strategies' },
          { id: 'sd109', name: 'What is SQL injection and how do you prevent it?' },
          { id: 'sd110', name: 'Explain the principle of least privilege' },
          { id: 'sd111', name: 'What is defense in depth?' },
          { id: 'sd112', name: 'Describe how to securely store and manage secrets (API keys, DB passwords)' },
          { id: 'sd113', name: 'What is a man-in-the-middle attack and how does TLS prevent it?' },
          { id: 'sd114', name: 'Explain rate limiting for API security' },
          { id: 'sd115', name: 'What is input validation and why is server-side validation critical?' },
          { id: 'sd116', name: 'Describe audit logging — what events should you log?' },
        ],
      },
      {
        id: 'sd-common-designs',
        title: 'Common System Design Problems',
        items: [
          { id: 'sd117', name: 'Design a URL shortener (e.g., bit.ly)', note: 'Shortening, redirect, analytics, scalability' },
          { id: 'sd118', name: 'Design a rate limiter', note: 'Token bucket, distributed state, SLAs' },
          { id: 'sd119', name: 'Design a chat system (e.g., WhatsApp)', note: 'Real-time, offline, read receipts, encryption' },
          { id: 'sd120', name: 'Design a notification system', note: 'Multi-channel, fan-out, delivery guarantees' },
          { id: 'sd121', name: 'Design a social media feed (e.g., Twitter)', note: 'Fan-out, timeline generation, caching' },
          { id: 'sd122', name: 'Design a search engine or autocomplete feature' },
          { id: 'sd123', name: 'Design a video streaming service (e.g., Netflix)' },
          { id: 'sd124', name: 'Design a distributed cache (e.g., Redis cluster)' },
          { id: 'sd125', name: 'Design a distributed message queue (e.g., Kafka)' },
          { id: 'sd126', name: 'Design a rate-limited API with multiple data centers' },
          { id: 'sd127', name: 'Design a file storage service (e.g., Dropbox / S3)' },
          { id: 'sd128', name: 'Design an auction system (e.g., eBay)' },
          { id: 'sd129', name: 'Design a proximity server (e.g., Yelp / Uber Eats nearby)' },
          { id: 'sd130', name: 'Design a WebSocket-based multiplayer game' },
          { id: 'sd131', name: 'Design an elevator system for a smart building' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 4. MICROSERVICES
  // ══════════════════════════════════════════════════════════════════════════════
  microservices: {
    sections: [
      {
        id: 'ms-architecture',
        title: 'Architecture Patterns',
        items: [
          { id: 'ms1', name: 'What are the benefits and drawbacks of microservices vs. monoliths?' },
          { id: 'ms2', name: 'What is a module monolith vs. microservices? When to migrate?' },
          { id: 'ms3', name: 'Explain the strangler fig pattern for gradually decomposing a monolith' },
          { id: 'ms4', name: 'What is the single responsibility principle in the context of microservices?' },
          { id: 'ms5', name: 'How do you define service boundaries? What is domain-driven design (DDD)?' },
          { id: 'ms6', name: 'Explain bounded contexts and why they matter for service boundaries' },
          { id: 'ms7', name: 'What is the anti-corruption layer pattern?' },
          { id: 'ms8', name: 'Describe the shared database vs. database-per-service pattern' },
          { id: 'ms9', name: 'What is an API gateway? What problems does it solve?' },
          { id: 'ms10', name: 'Explain backend-for-frontend (BFF) pattern and when to use it' },
          { id: 'ms11', name: 'What is an aggregator pattern in microservices?' },
          { id: 'ms12', name: 'Describe the sidecar pattern and its use cases' },
          { id: 'ms13', name: 'What is the ambassador pattern?' },
          { id: 'ms14', name: 'Explain the difference between tight coupling and loose coupling' },
          { id: 'ms15', name: 'What is service autonomy? Why does it matter?' },
        ],
      },
      {
        id: 'ms-api-design',
        title: 'API Design & Contracts',
        items: [
          { id: 'ms16', name: 'How do you design RESTful APIs for microservices?' },
          { id: 'ms17', name: 'What is REST maturity model (Richardson Maturity Model)?' },
          { id: 'ms18', name: 'Describe API versioning strategies and their trade-offs' },
          { id: 'ms19', name: 'What is a consumer-driven contract test (CDC)?' },
          { id: 'ms20', name: 'How do you handle backward compatibility in API changes?' },
          { id: 'ms21', name: 'What is OpenAPI/Swagger and why is it useful?' },
          { id: 'ms22', name: 'Describe GraphQL federation for microservices' },
          { id: 'ms23', name: 'What are the pros and cons of GraphQL vs. REST for service-to-service communication?' },
          { id: 'ms24', name: 'Explain how you would design a service that other services depend on' },
          { id: 'ms25', name: 'What is a public API vs. internal API? How do the design considerations differ?' },
          { id: 'ms26', name: 'How do you handle pagination in APIs? Compare cursor-based vs. offset-based' },
          { id: 'ms27', name: 'What is idempotent API design and why does it matter in microservices?' },
        ],
      },
      {
        id: 'ms-distributed-tx',
        title: 'Distributed Transactions',
        items: [
          { id: 'ms28', name: 'Why are distributed transactions hard? Describe the 2-phase commit protocol' },
          { id: 'ms29', name: 'What are the limitations of 2-phase commit?' },
          { id: 'ms30', name: 'Explain the saga pattern and how it differs from 2PC' },
          { id: 'ms31', name: 'Describe choreography-based saga vs. orchestration-based saga' },
          { id: 'ms32', name: 'What are compensating transactions in a saga?' },
          { id: 'ms33', name: 'How do you handle partial failures in saga patterns?' },
          { id: 'ms34', name: 'What is the outbox pattern for reliable event publishing?' },
          { id: 'ms35', name: 'Explain the dual write problem and how to avoid it' },
          { id: 'ms36', name: 'What is eventual consistency? How do you reason about it in business logic?' },
          { id: 'ms37', name: 'Describe how to implement saga with choreography using events' },
          { id: 'ms38', name: 'What is the transactional outbox pattern implementation with CDC?' },
        ],
      },
      {
        id: 'ms-service-mesh',
        title: 'Service Mesh & Infrastructure',
        items: [
          { id: 'ms39', name: 'What is a service mesh? Name examples (Istio, Linkerd, Envoy)' },
          { id: 'ms40', name: 'Explain sidecar proxies and how they work in a service mesh' },
          { id: 'ms41', name: 'What is mTLS (mutual TLS)? Why is it important in a service mesh?' },
          { id: 'ms42', name: 'Describe how service mesh handles load balancing at L7' },
          { id: 'ms43', name: 'What is a circuit breaker in the context of service mesh?' },
          { id: 'ms44', name: 'Explain how service mesh handles retries and timeouts' },
          { id: 'ms45', name: 'What is canary deployment and how does service mesh support it?' },
          { id: 'ms46', name: 'Describe traffic shadowing / mirroring for production testing' },
          { id: 'ms47', name: 'What is observability in a service mesh context? How does it work?' },
          { id: 'ms48', name: 'What are the operational overheads of adopting a service mesh?' },
          { id: 'ms49', name: 'Explain the difference between host networking and CNI in Kubernetes' },
          { id: 'ms50', name: 'What is a service entry in Istio?' },
        ],
      },
      {
        id: 'ms-observability',
        title: 'Observability & Debugging',
        items: [
          { id: 'ms51', name: 'How do you trace a request across multiple microservices?' },
          { id: 'ms52', name: 'What is a trace ID vs. span ID? How do they propagate?' },
          { id: 'ms53', name: 'Describe the three pillars of observability in a microservices context' },
          { id: 'ms54', name: 'What is the difference between structured logging and plain text logs?' },
          { id: 'ms55', name: 'How would you implement distributed tracing from scratch?' },
          { id: 'ms56', name: 'What is the "golden signal" approach to monitoring microservices?' },
          { id: 'ms57', name: 'How do you debug a latency issue across a chain of 10 services?' },
          { id: 'ms58', name: 'What is a tail-based vs. head-based sampling in distributed tracing?' },
          { id: 'ms59', name: 'Describe how to set up alerting for microservices with SLOs' },
          { id: 'ms60', name: 'What is correlation ID and how do you propagate it through service calls?' },
        ],
      },
      {
        id: 'ms-deployment',
        title: 'Deployment & Operations',
        items: [
          { id: 'ms61', name: 'Describe the blue-green deployment strategy' },
          { id: 'ms62', name: 'Describe the canary deployment strategy and how to monitor it' },
          { id: 'ms63', name: 'What is a rolling deployment? What are its trade-offs?' },
          { id: 'ms64', name: 'Explain immutable infrastructure and its benefits' },
          { id: 'ms65', name: 'What is container orchestration? Why is Kubernetes the standard?' },
          { id: 'ms66', name: 'Describe how you would manage configuration across environments' },
          { id: 'ms67', name: 'What is a Helm chart? How do you structure one for a microservice?' },
          { id: 'ms68', name: 'Explain the difference between liveness and readiness probes' },
          { id: 'ms69', name: 'How do you handle database migrations in a microservices deployment?' },
          { id: 'ms70', name: 'What is the strangler fig pattern for incrementally migrating a monolith?' },
          { id: 'ms71', name: 'Describe how you would implement zero-downtime deployments' },
          { id: 'ms72', name: 'What is blue-green database migration pattern?' },
        ],
      },
      {
        id: 'ms-resilience',
        title: 'Resilience Engineering',
        items: [
          { id: 'ms73', name: 'Explain the circuit breaker pattern and its states (closed, open, half-open)' },
          { id: 'ms74', name: 'What is bulkhead isolation in microservices?' },
          { id: 'ms75', name: 'Describe retry strategies: when to retry, when not to, and backoff strategies' },
          { id: 'ms76', name: 'What is a timeout strategy for inter-service calls?' },
          { id: 'ms77', name: 'Explain deadline propagation across service calls' },
          { id: 'ms78', name: 'What is a fallback and when would you use it?' },
          { id: 'ms79', name: 'How do you design for graceful degradation?' },
          { id: 'ms80', name: 'What is the difference between fault tolerance and high availability?' },
          { id: 'ms81', name: 'Describe chaos engineering practices specific to microservices' },
          { id: 'ms82', name: 'What is proactive vs. reactive capacity planning?' },
          { id: 'ms83', name: 'How do you handle distributed tracing correlation for failure analysis?' },
          { id: 'ms84', name: 'Describe load shedding strategies to protect core functionality under load' },
        ],
      },
      {
        id: 'ms-security',
        title: 'Microservices Security',
        items: [
          { id: 'ms85', name: 'How do you handle authentication in a microservices architecture?' },
          { id: 'ms86', name: 'What is the difference between a service token and a user token?' },
          { id: 'ms87', name: 'Explain how JWT tokens work and their security considerations' },
          { id: 'ms88', name: 'What is a token introspection endpoint?' },
          { id: 'ms89', name: 'How do you implement authorization (RBAC/ABAC) across services?' },
          { id: 'ms90', name: 'What is the principle of defense in depth for microservices?' },
          { id: 'ms91', name: 'How do you secure service-to-service communication?' },
          { id: 'ms92', name: 'What is a service mesh doing for security that you cannot do without one?' },
          { id: 'ms93', name: 'Describe network policies in Kubernetes and how they isolate services' },
          { id: 'ms94', name: 'What is a SPIFFE/SPIRE framework for workload identity?' },
          { id: 'ms95', name: 'How do you handle secrets management across microservices?' },
          { id: 'ms96', name: 'What is an incident response plan for a microservices platform?' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 5. DATABASES
  // ══════════════════════════════════════════════════════════════════════════════
  databases: {
    sections: [
      {
        id: 'db-sql-fundamentals',
        title: 'SQL Fundamentals',
        items: [
          { id: 'db1', name: 'Write a query to find the nth highest salary in a table' },
          { id: 'db2', name: 'Write a query to find duplicate rows in a table' },
          { id: 'db3', name: 'Explain the difference between INNER, LEFT, RIGHT, and FULL OUTER JOIN' },
          { id: 'db4', name: 'What is the difference between WHERE and HAVING?' },
          { id: 'db5', name: 'Explain the order of execution of a SQL query', note: 'FROM -> JOIN -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY -> LIMIT' },
          { id: 'db6', name: 'What is the difference between UNION and UNION ALL?' },
          { id: 'db7', name: 'What is a self-join? Give a practical use case' },
          { id: 'db8', name: 'Write a query to compute a running total / cumulative sum' },
          { id: 'db9', name: 'What is window function? Give examples of ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD' },
          { id: 'db10', name: 'Explain CTEs (Common Table Expressions) vs. subqueries — when to use each' },
          { id: 'db11', name: 'Write a query to find gaps in a sequence of numbers (e.g., missing IDs)' },
          { id: 'db12', name: 'What is a pivot/unpivot query?' },
          { id: 'db13', name: 'How do you handle NULL values in aggregations (SUM, AVG, COUNT)?' },
          { id: 'db14', name: 'Explain COALESCE and CASE WHEN for conditional logic in SQL' },
        ],
      },
      {
        id: 'db-indexing',
        title: 'Indexing & Performance',
        items: [
          { id: 'db15', name: 'How does a B-tree index work? Why is it efficient for range queries?' },
          { id: 'db16', name: 'What is the difference between a clustered and non-clustered index?' },
          { id: 'db17', name: 'What is a composite index? What is column order importance?' },
          { id: 'db18', name: 'What is an index covering query (covering index)?' },
          { id: 'db19', name: 'What is index selectivity and why does it matter?' },
          { id: 'db20', name: 'Explain partial / filtered indexes and their use cases' },
          { id: 'db21', name: 'What is a unique index and how does it differ from a primary key?' },
          { id: 'db22', name: 'When should you NOT add an index? What are the downsides?' },
          { id: 'db23', name: 'How do you identify slow queries? Tools and techniques?', note: 'EXPLAIN ANALYZE, slow query log, pg_stat_statements' },
          { id: 'db24', name: 'Explain EXPLAIN ANALYZE output — what are the key metrics?', note: 'Seq Scan, Index Scan, Nested Loop, Hash Join, Sort' },
          { id: 'db25', name: 'What is a hash join vs. merge join vs. nested loop join? When is each used?' },
          { id: 'db26', name: 'What is a table scan vs. an index scan? When does the query planner choose each?' },
          { id: 'db27', name: 'What is index bloat and how do you defragment it?' },
          { id: 'db28', name: 'How do you optimize a query with multiple JOINs and subqueries?' },
          { id: 'db29', name: 'What is a materialized view vs. a regular view? When to use each?' },
          { id: 'db30', name: 'What is query plan caching? How does it affect performance?' },
        ],
      },
      {
        id: 'db-transactions',
        title: 'Transactions & Concurrency',
        items: [
          { id: 'db31', name: 'Explain ACID properties in detail' },
          { id: 'db32', name: 'What is the difference between pessimistic and optimistic locking?' },
          { id: 'db33', name: 'What is a lock? Name different types: shared, exclusive, row-level, table-level' },
          { id: 'db34', name: 'What is a deadlock? How do databases detect and resolve deadlocks?' },
          { id: 'db35', name: 'How do you prevent deadlocks in application code?' },
          { id: 'db36', name: 'What is transaction isolation level? List all four standard levels' },
          { id: 'db37', name: 'What problems does each isolation level prevent: dirty read, non-repeatable read, phantom read?' },
          { id: 'db38', name: 'What is MVCC (Multi-Version Concurrency Control)?' },
          { id: 'db39', name: 'What is read committed vs. read uncommitted vs. serializable?' },
          { id: 'db40', name: 'What is a phantom read and which isolation level prevents it?' },
          { id: 'db41', name: 'What is a long-running transaction and why is it problematic?' },
          { id: 'db42', name: 'How does savepoint work in a transaction?' },
          { id: 'db43', name: 'What is two-phase locking (2PL)?' },
        ],
      },
      {
        id: 'db-nosql',
        title: 'NoSQL Databases',
        items: [
          { id: 'db44', name: 'What are the four categories of NoSQL databases? Give examples of each' },
          { id: 'db45', name: 'Explain key-value stores: use cases, examples (Redis, DynamoDB)' },
          { id: 'db46', name: 'Explain document stores: use cases, examples (MongoDB, CouchDB)' },
          { id: 'db47', name: 'Explain wide-column stores: use cases, examples (Cassandra, HBase)' },
          { id: 'db48', name: 'Explain graph databases: use cases, examples (Neo4j, Amazon Neptune)' },
          { id: 'db49', name: 'When would you choose DynamoDB over a relational database?' },
          { id: 'db50', name: 'What is eventual consistency in DynamoDB? How does it relate to consistency levels?' },
          { id: 'db51', name: 'Explain DynamoDB single-table design pattern' },
          { id: 'db52', name: 'What is the difference between sharding and partitioning in NoSQL?' },
          { id: 'db53', name: 'What is a tombstone in a distributed database? When are records finally deleted?' },
          { id: 'db54', name: 'What is compaction in LSM-tree based databases (Cassandra, RocksDB)?' },
          { id: 'db55', name: 'How does Cassandra handle writes and what is its consistency model?' },
          { id: 'db56', name: 'What is the CAP theorem trade-off for Cassandra vs. MongoDB?' },
          { id: 'db57', name: 'When would you use a search database (Elasticsearch) over a relational DB?' },
        ],
      },
      {
        id: 'db-data-modeling',
        title: 'Data Modeling',
        items: [
          { id: 'db58', name: 'How do you model a many-to-many relationship in SQL?' },
          { id: 'db59', name: 'What is database normalization? List 1NF, 2NF, 3NF, BCNF and their rules' },
          { id: 'db60', name: 'When should you denormalize? What are the trade-offs?' },
          { id: 'db61', name: 'What is an adjacency list model for hierarchical data?' },
          { id: 'db62', name: 'How do you model tree structures in a relational database?', note: 'Adjacency list, nested sets, closure table' },
          { id: 'db63', name: 'What is the materialization path pattern for hierarchical data?' },
          { id: 'db64', name: 'How do you design a schema for time-series data?' },
          { id: 'db65', name: 'What is a slowly changing dimension (SCD) in data warehousing?' },
          { id: 'db66', name: 'Describe Type 1, Type 2, and Type 3 SCD approaches' },
          { id: 'db67', name: 'What is a star schema vs. snowflake schema in data warehousing?' },
          { id: 'db68', name: 'What is a fact table vs. dimension table?' },
          { id: 'db69', name: 'What are degenerate dimensions in a fact table?' },
          { id: 'db70', name: 'How do you model polymorphic associations in a relational database?' },
        ],
      },
      {
        id: 'db-replication',
        title: 'Replication & High Availability',
        items: [
          { id: 'db71', name: 'What is primary-replica replication? Describe the architecture' },
          { id: 'db72', name: 'Explain synchronous vs. asynchronous replication — trade-offs' },
          { id: 'db73', name: 'What is semi-synchronous replication?' },
          { id: 'db74', name: 'Describe statement-based vs. row-based vs. mixed binary log replication' },
          { id: 'db75', name: 'What is read replica lag and how do you monitor it?' },
          { id: 'db76', name: 'What is multi-source replication?' },
          { id: 'db77', name: 'How do you handle failover in a primary-replica setup?' },
          { id: 'db78', name: 'What is a virtual IP (VIP) in the context of database failover?' },
          { id: 'db79', name: 'What is split-brain in database replication? How do you prevent it?' },
          { id: 'db80', name: 'What is a distributed consensus algorithm relevant to DB replication?', note: 'Raft, Paxos — leader election, log replication' },
          { id: 'db81', name: 'What is Vitess and how does it handle MySQL sharding at scale?' },
          { id: 'db82', name: 'How does CockroachDB or Spanner achieve distributed consistency?' },
          { id: 'db83', name: 'What is the CAP theorem implication for multi-region database deployments?' },
        ],
      },
      {
        id: 'db-sharding',
        title: 'Sharding & Partitioning',
        items: [
          { id: 'db84', name: 'What is database sharding? How does it differ from partitioning?' },
          { id: 'db85', name: 'Describe hash-based sharding and its limitations' },
          { id: 'db86', name: 'What is range-based sharding and when is it appropriate?' },
          { id: 'db87', name: 'What is consistent hashing and how does it help with resharding?' },
          { id: 'db88', name: 'What is the shard key? How do you choose an optimal shard key?' },
          { id: 'db89', name: 'What are the challenges of cross-shard queries and joins?' },
          { id: 'db90', name: 'What is a distributed transaction across shards?' },
          { id: 'db91', name: 'What is shard rebalancing / resharding and why is it hard?' },
          { id: 'db92', name: 'What is the data migration challenge when adding a new shard?' },
          { id: 'db93', name: "How does MongoDB's sharding architecture work?" },
          { id: 'db94', name: 'What is a mongos router and config server in MongoDB sharding?' },
          { id: 'db95', name: 'What is the chunk migration process in MongoDB?' },
          { id: 'db96', name: 'What is the difference between horizontal partitioning and sharding?' },
          { id: 'db97', name: 'How do you choose between application-level sharding and database-native sharding?' },
        ],
      },
      {
        id: 'db-advanced',
        title: 'Advanced Topics',
        items: [
          { id: 'db98', name: 'What is the difference between OLTP and OLAP workloads?' },
          { id: 'db99', name: 'What is a columnar database and why is it efficient for analytics?' },
          { id: 'db100', name: 'What is vector database? When would you use it?', note: 'Pinecone, Weaviate, pgvector for embeddings' },
          { id: 'db101', name: 'What is change data capture (CDC)? Name tools (Debezium, AWS DMS)' },
          { id: 'db102', name: 'What is a data pipeline? How do you handle late-arriving data?' },
          { id: 'db103', name: 'What is the write-ahead log (WAL) and how does it relate to durability?' },
          { id: 'db104', name: 'What is database connection pooling? Name tools (HikariCP, PgBouncer)' },
          { id: 'db105', name: 'What is the N+1 query problem and how do you solve it?' },
          { id: 'db106', name: 'What is a surrogate key vs. natural key?' },
          { id: 'db107', name: 'What is a sequence / auto-increment vs. UUID as a primary key?' },
          { id: 'db108', name: 'What is the difference between a data warehouse, data lake, and data mesh?' },
          { id: 'db109', name: 'What is Apache Iceberg / Delta Lake / Apache Hudi for data lakes?' },
          { id: 'db110', name: 'What is the difference between lakehouse architecture and traditional data warehouse?' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 6. COMPUTER SCIENCE FUNDAMENTALS
  // ══════════════════════════════════════════════════════════════════════════════
  'cs-fundamentals': {
    sections: [
      {
        id: 'cs-complexity',
        title: 'Complexity Analysis',
        items: [
          { id: 'cs1', name: 'Define Big O, Big Omega, and Big Theta notation' },
          { id: 'cs2', name: 'What is the difference between O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n), O(n!)' },
          { id: 'cs3', name: 'Analyze the time and space complexity of a given algorithm' },
          { id: 'cs4', name: 'What is amortized analysis? Give an example (e.g., dynamic array resizing)' },
          { id: 'cs5', name: 'What is a recurrence relation? How do you solve them?' },
          { id: 'cs6', name: 'Explain Master Theorem and its limitations' },
          { id: 'cs7', name: 'What is the difference between best, worst, and average case analysis?' },
          { id: 'cs8', name: 'What is space complexity? How do you analyze it?' },
          { id: 'cs9', name: 'What is a constant factor in complexity analysis?' },
          { id: 'cs10', name: 'How do you analyze algorithms with multiple parameters (e.g., O(n + k))?' },
        ],
      },
      {
        id: 'cs-sorting',
        title: 'Sorting Algorithms',
        items: [
          { id: 'cs11', name: 'Implement and analyze: Bubble Sort — O(n^2), stable' },
          { id: 'cs12', name: 'Implement and analyze: Selection Sort — O(n^2), unstable' },
          { id: 'cs13', name: 'Implement and analyze: Insertion Sort — O(n^2) worst/avg, O(n) best' },
          { id: 'cs14', name: 'Implement and analyze: Merge Sort — O(n log n), stable, divide-and-conquer' },
          { id: 'cs15', name: 'Implement and analyze: Quick Sort — O(n log n) avg, O(n^2) worst, unstable' },
          { id: 'cs16', name: 'Implement and analyze: Heap Sort — O(n log n), unstable' },
          { id: 'cs17', name: 'What is the difference between stable and unstable sorting?' },
          { id: 'cs18', name: 'What is in-place sorting vs. out-of-place sorting?' },
          { id: 'cs19', name: 'Why is Quick Sort preferred over Merge Sort in practice despite same average complexity?' },
          { id: 'cs20', name: 'What is timsort / introsort? Why do modern languages use them?' },
          { id: 'cs21', name: 'What is the lower bound for comparison-based sorting? What sorts achieve it?' },
          { id: 'cs22', name: 'What is counting sort / radix sort / bucket sort — when are they used?' },
          { id: 'cs23', name: 'How do you find the kth largest element in O(n) average time?' },
        ],
      },
      {
        id: 'cs-searching',
        title: 'Searching Algorithms',
        items: [
          { id: 'cs24', name: 'Implement and analyze: Linear Search — O(n)' },
          { id: 'cs25', name: 'Implement and analyze: Binary Search — O(log n) on sorted arrays' },
          { id: 'cs26', name: 'What is the variant of binary search for finding the first/last occurrence?' },
          { id: 'cs27', name: 'What is binary search on the answer (search on monotonic predicate)?' },
          { id: 'cs28', name: 'Implement and analyze: Depth-First Search (DFS) on a graph' },
          { id: 'cs29', name: 'Implement and analyze: Breadth-First Search (BFS) on a graph' },
          { id: 'cs30', name: 'What is Dijkstra\'s algorithm? When does it fail? Analyze complexity' },
          { id: 'cs31', name: 'What is Bellman-Ford algorithm? Can it handle negative weights?' },
          { id: 'cs32', name: 'What is A* search? What is a good heuristic?' },
          { id: 'cs33', name: 'What is the difference between BFS and DFS in terms of space complexity?' },
          { id: 'cs34', name: 'Explain the difference between uniform-cost search and Dijkstra\'s algorithm' },
        ],
      },
      {
        id: 'cs-ds-arrays',
        title: 'Arrays & Strings',
        items: [
          { id: 'cs35', name: 'What are the time complexities of basic array operations? (access, insert, delete)' },
          { id: 'cs36', name: 'What is the difference between an array and a dynamic array (ArrayList)?' },
          { id: 'cs37', name: 'How does dynamic array resizing work? What is the amortized cost?' },
          { id: 'cs38', name: 'What is a subarray, subsequence, substring, and subset? Differences?' },
          { id: 'cs39', name: 'Two-pointer technique: sliding window problems' },
          { id: 'cs40', name: 'What is prefix sum? When is it useful?' },
          { id: 'cs41', name: 'What is a rolling hash? How is it used in string matching?' },
          { id: 'cs42', name: 'What is KMP algorithm and how does the LPS (longest prefix suffix) array work?' },
          { id: 'cs43', name: 'What is the Z-function / Z-algorithm for string matching?' },
          { id: 'cs44', name: 'What is Manacher\'s algorithm for longest palindromic substring?' },
          { id: 'cs45', name: 'What is the difference between a hash map and an array for string problems?' },
        ],
      },
      {
        id: 'cs-ds-linkedlist',
        title: 'Linked Lists',
        items: [
          { id: 'cs46', name: 'What are the time complexities of operations on singly vs. doubly linked lists?' },
          { id: 'cs47', name: 'How do you detect a cycle in a linked list? Explain Floyd\'s cycle detection' },
          { id: 'cs48', name: 'How do you find the start of a cycle in a linked list?' },
          { id: 'cs49', name: 'How do you find the middle of a linked list in one pass?' },
          { id: 'cs50', name: 'How do you reverse a linked list iteratively? Recursively?' },
          { id: 'cs51', name: 'How do you reverse a singly linked list in groups of k?' },
          { id: 'cs52', name: 'What is the difference between shallow copy and deep copy?' },
          { id: 'cs53', name: 'How do you clone a linked list with random pointers?' },
          { id: 'cs54', name: 'What is LRU cache and how is it implemented with a doubly linked list + hash map?' },
        ],
      },
      {
        id: 'cs-ds-stacksqueues',
        title: 'Stacks & Queues',
        items: [
          { id: 'cs55', name: 'Implement a stack with push, pop, peek, and O(1) min operation' },
          { id: 'cs56', name: 'What is a monotonic stack? When is it used?' },
          { id: 'cs57', name: 'Implement a queue using two stacks' },
          { id: 'cs58', name: 'Implement a stack using two queues' },
          { id: 'cs59', name: 'What is a priority queue? How is it typically implemented?' },
          { id: 'cs60', name: 'What is a deque (double-ended queue)?' },
          { id: 'cs61', name: 'Explain the sliding window maximum problem and the deque solution' },
          { id: 'cs62', name: 'What is the Next Greater Element problem and its monotonic stack solution?' },
          { id: 'cs63', name: 'How do you evaluate a postfix expression using a stack?' },
          { id: 'cs64', name: 'How do you convert infix to postfix using a stack?' },
        ],
      },
      {
        id: 'cs-ds-trees',
        title: 'Trees',
        items: [
          { id: 'cs65', name: 'Define and implement: Binary Tree, Binary Search Tree (BST), AVL Tree, Red-Black Tree' },
          { id: 'cs66', name: 'What is the time complexity of search, insert, and delete in a BST (balanced vs. unbalanced)?' },
          { id: 'cs67', name: 'What is tree traversal? Implement: Inorder, Preorder, Postorder (recursive and iterative)' },
          { id: 'cs68', name: 'What is level-order traversal (BFS on tree)?' },
          { id: 'cs69', name: 'How do you find the lowest common ancestor (LCA) in a binary tree?' },
          { id: 'cs70', name: 'How do you serialize and deserialize a binary tree?' },
          { id: 'cs71', name: 'What is a segment tree and what problems does it solve?' },
          { id: 'cs72', name: 'What is a binary indexed tree (Fenwick Tree) and what problems does it solve?' },
          { id: 'cs73', name: 'What is a trie (prefix tree)? Implement insert and search' },
          { id: 'cs74', name: 'What is the difference between a binary heap, min-heap, and max-heap?' },
          { id: 'cs75', name: 'How do you implement a heap from scratch? (heapify, bubble up/down)' },
          { id: 'cs76', name: 'What is a Fibonacci heap? What are its amortized complexities?' },
          { id: 'cs77', name: 'What is a B-tree and B+ tree? Why are they used in databases?' },
          { id: 'cs78', name: 'What is the difference between a binary tree and a B-tree\'s branching factor?' },
          { id: 'cs79', name: 'How do you balance an unbalanced BST?' },
          { id: 'cs80', name: 'What is treap (randomized BST)?' },
        ],
      },
      {
        id: 'cs-ds-graphs',
        title: 'Graphs',
        items: [
          { id: 'cs81', name: 'What are the two main representations of a graph? (Adjacency list vs. matrix)' },
          { id: 'cs82', name: 'What is the difference between directed and undirected graphs?' },
          { id: 'cs83', name: 'What is a weighted graph vs. unweighted graph?' },
          { id: 'cs84', name: 'Implement DFS and BFS on a graph' },
          { id: 'cs85', name: 'What is topological sort? When does it apply? Implement it' },
          { id: 'cs86', name: 'What is a cycle in a graph? How do you detect it?' },
          { id: 'cs87', name: 'Implement union-find (disjoint set union) data structure' },
          { id: 'cs88', name: 'What is the time complexity of union-find with path compression and union by rank?' },
          { id: 'cs89', name: 'What are strongly connected components (SCC)? How do you find them?', note: 'Tarjan\'s algorithm, Kosaraju\'s algorithm' },
          { id: 'cs90', name: 'What is Dijkstra\'s algorithm? Implement it with a priority queue' },
          { id: 'cs91', name: 'What is the difference between Dijkstra and Bellman-Ford?' },
          { id: 'cs92', name: 'What is the Bellman-Ford algorithm? How does it handle negative weight cycles?' },
          { id: 'cs93', name: 'What is the Floyd-Warshall algorithm? Analyze its complexity' },
          { id: 'cs94', name: 'What is a minimum spanning tree (MST)? Implement Prim\'s and Kruskal\'s algorithms' },
          { id: 'cs95', name: 'What is a bipartite graph? How do you check if a graph is bipartite?' },
          { id: 'cs96', name: 'What is Eulerian path/circuit vs. Hamiltonian path/cycle?' },
          { id: 'cs97', name: 'What is a graph cut? What is a minimum cut?' },
        ],
      },
      {
        id: 'cs-dp',
        title: 'Dynamic Programming',
        items: [
          { id: 'cs98', name: 'What are the optimal substructure and overlapping subproblems properties?' },
          { id: 'cs99', name: 'What is the difference between top-down (memoization) and bottom-up (tabulation) DP?' },
          { id: 'cs100', name: 'What is space optimization in DP? How do you reduce O(n^2) space to O(n)?' },
          { id: 'cs101', name: 'What is DP on subsequences vs. DP on subsets vs. DP on intervals?' },
          { id: 'cs102', name: 'What is DP with bitmasking? When is it used?' },
          { id: 'cs103', name: 'What is DP optimization: divide and conquer optimization?' },
          { id: 'cs104', name: 'What is DP optimization: convex hull trick / monotone queue?' },
          { id: 'cs105', name: 'What is DP optimization: Knuth optimization?' },
          { id: 'cs106', name: 'Implement: 0/1 Knapsack — variations (subset sum, equal partition, target sum)' },
          { id: 'cs107', name: 'Implement: Longest Common Subsequence (LCS) and Edit Distance' },
          { id: 'cs108', name: 'Implement: Longest Increasing Subsequence (LIS) — O(n^2) and O(n log n) solutions' },
          { id: 'cs109', name: 'Implement: Coin Change (minimum coins, number of ways)' },
          { id: 'cs110', name: 'Implement: House Robber (linear, circular, with adjacent houses conflict)' },
          { id: 'cs111', name: 'Implement: DP on trees — maximum path sum, diameter of tree' },
          { id: 'cs112', name: 'Implement: DP on graphs — number of paths, shortest paths with DP' },
          { id: 'cs113', name: 'What is matrix exponentiation for DP (e.g., Fibonacci, number of paths in grid)?' },
        ],
      },
      {
        id: 'cs-greedy',
        title: 'Greedy Algorithms',
        items: [
          { id: 'cs114', name: 'What is the greedy choice property? How does it differ from DP?' },
          { id: 'cs115', name: 'When is a greedy algorithm correct vs. when might it fail?' },
          { id: 'cs116', name: 'Implement activity selection problem with greedy' },
          { id: 'cs117', name: 'Implement fractional knapsack with greedy' },
          { id: 'cs118', name: 'Explain Huffman coding — greedy construction of optimal prefix code' },
          { id: 'cs119', name: 'What is the proof of correctness for greedy algorithms?' },
          { id: 'cs120', name: 'Why does the 0/1 knapsack require DP but fractional knapsack can use greedy?' },
          { id: 'cs121', name: 'What is the difference between Prim\'s and Kruskal\'s MST algorithms?' },
        ],
      },
      {
        id: 'cs-hashing',
        title: 'Hashing',
        items: [
          { id: 'cs122', name: 'What is a hash function? What makes a good hash function?' },
          { id: 'cs123', name: 'What is a collision? Name collision resolution strategies', note: 'Chaining (linked list), open addressing (linear probing, quadratic probing, double hashing)' },
          { id: 'cs124', name: 'What is the load factor in a hash table? How does rehashing work?' },
          { id: 'cs125', name: 'What is consistent hashing and why is it used in distributed systems?' },
          { id: 'cs126', name: 'What is a hash map vs. a hash set?' },
          { id: 'cs127', name: 'What is a bloom filter? What are false positives vs. false negatives?' },
          { id: 'cs128', name: 'What is a count-min sketch for frequency estimation?' },
        ],
      },
      {
        id: 'cs-bitmanipulation',
        title: 'Bit Manipulation',
        items: [
          { id: 'cs129', name: 'Implement: get bit, set bit, clear bit, update bit using bitwise operators' },
          { id: 'cs130', name: 'What is the difference between &, |, ^, ~, <<, >> operators?' },
          { id: 'cs131', name: 'What is two\'s complement representation of negative numbers?' },
          { id: 'cs132', name: 'How do you check if a number is a power of 2 using bit operations?' },
          { id: 'cs133', name: 'How do you swap two numbers without a temporary variable using XOR?' },
          { id: 'cs134', name: 'What is bitmask DP? Give an example problem' },
          { id: 'cs135', name: 'Implement a bitmask solution for the traveling salesman problem' },
          { id: 'cs136', name: 'What is the trick to count the number of set bits in an integer?' },
          { id: 'cs137', name: 'What is the difference between signed and unsigned right shift?' },
        ],
      },
      {
        id: 'cs-recursion',
        title: 'Recursion & Backtracking',
        items: [
          { id: 'cs138', name: 'What is the difference between recursion and iteration? When to use each?' },
          { id: 'cs139', name: 'What is tail recursion? How does it relate to stack overflow?' },
          { id: 'cs140', name: 'What is backtracking? How does it differ from recursion?' },
          { id: 'cs141', name: 'Implement N-Queens problem using backtracking' },
          { id: 'cs142', name: 'Implement Sudoku solver using backtracking' },
          { id: 'cs143', name: 'Implement subset generation and combination sum using backtracking' },
          { id: 'cs144', name: 'What is memoization in the context of recursion?' },
          { id: 'cs145', name: 'What is the call stack? What causes stack overflow?' },
          { id: 'cs146', name: 'How do you convert a recursive algorithm to iterative?' },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 7. MATHEMATICS & PROBABILITY
  // ══════════════════════════════════════════════════════════════════════════════
  math: {
    sections: [
      {
        id: 'm-probability-basics',
        title: 'Probability Basics',
        items: [
          { id: 'm1', name: 'Define: sample space, event, probability of an event' },
          { id: 'm2', name: 'What is P(A and B) for independent vs. dependent events?' },
          { id: 'm3', name: 'What is P(A or B) for mutually exclusive vs. non-mutually exclusive events?' },
          { id: 'm4', name: 'What is conditional probability? P(A | B) = ?' },
          { id: 'm5', name: 'What is the law of total probability?' },
          { id: 'm6', name: 'What is Bayes\' theorem? Derive it from conditional probability' },
          { id: 'm7', name: 'What is a probability distribution? Name discrete and continuous distributions' },
          { id: 'm8', name: 'What are the expected value and variance of a random variable?' },
          { id: 'm9', name: 'What is linearity of expectation? Can you give an example where it is counterintuitive?' },
          { id: 'm10', name: 'What is indicator random variable? How is it used in probability proofs?' },
          { id: 'm11', name: 'What is the difference between a discrete and continuous random variable?' },
          { id: 'm12', name: 'What is a cumulative distribution function (CDF)?' },
          { id: 'm13', name: 'What is the probability mass function (PMF) vs. probability density function (PDF)?' },
        ],
      },
      {
        id: 'm-distributions',
        title: 'Common Distributions',
        items: [
          { id: 'm14', name: 'Describe the Bernoulli distribution — mean and variance' },
          { id: 'm15', name: 'Describe the Binomial distribution — formula, mean, variance' },
          { id: 'm16', name: 'Describe the Geometric distribution — formula, mean' },
          { id: 'm17', name: 'Describe the Negative Binomial / Pascal distribution' },
          { id: 'm18', name: 'Describe the Poisson distribution — formula, mean, variance, use cases' },
          { id: 'm19', name: 'Describe the Uniform distribution (discrete and continuous)' },
          { id: 'm20', name: 'Describe the Normal (Gaussian) distribution — properties, 68-95-99.7 rule' },
          { id: 'm21', name: 'Describe the Exponential distribution — formula, mean, memoryless property' },
          { id: 'm22', name: 'Describe the Poisson process and its relationship to the exponential distribution' },
          { id: 'm23', name: 'What is a power-law / Zipf distribution? When does it appear?' },
          { id: 'm24', name: 'What is a log-normal distribution?' },
          { id: 'm25', name: 'What is the difference between Poisson and Binomial? When to use each?' },
          { id: 'm26', name: 'What is the Central Limit Theorem and why is it important?' },
          { id: 'm27', name: 'What is the Law of Large Numbers?' },
        ],
      },
      {
        id: 'm-combinatorics',
        title: 'Combinatorics',
        items: [
          { id: 'm28', name: 'What is the fundamental counting principle (product rule)?' },
          { id: 'm29', name: 'What is n! (factorial) and when is it used?' },
          { id: 'm30', name: 'What is the difference between permutation and combination?' },
          { id: 'm31', name: 'Derive and use the formula for combinations: C(n, k) = n! / (k!(n-k)!)' },
          { id: 'm32', name: 'What is C(n, k) = C(n, n-k)? Symmetry property of combinations' },
          { id: 'm33', name: 'What is Pascal\'s triangle and how does it relate to combinations?' },
          { id: 'm34', name: 'What is the sum of all combinations: Sum of C(n, k) for k=0..n = 2^n?' },
          { id: 'm35', name: 'What is a stars and bars (balls and urns) problem? When to use it?' },
          { id: 'm36', name: 'What is the inclusion-exclusion principle? P(A or B) = ?' },
          { id: 'm37', name: 'What is the pigeonhole principle? Give a non-trivial example' },
          { id: 'm38', name: 'How do you count permutations of multiset (when some items are identical)?' },
          { id: 'm39', name: 'What is the derangement problem (subfactorial)? D(n) formula' },
          { id: 'm40', name: 'How many ways are there to arrange n items in a circle?' },
          { id: 'm41', name: 'What is the number of ways to choose k items from n with repetition?' },
          { id: 'm42', name: 'What are Catalan numbers? Name problems that yield Catalan numbers', note: 'n-th Catalan = C(2n, n) / (n+1)' },
        ],
      },
      {
        id: 'm-conditional-prob',
        title: 'Conditional Probability & Bayes',
        items: [
          { id: 'm43', name: 'Compute conditional probability: P(A|B) given a probability table' },
          { id: 'm44', name: 'Use Bayes\' theorem to solve a medical test problem (sensitivity, specificity, prevalence)' },
          { id: 'm45', name: 'What is a prior, posterior, likelihood, and evidence in Bayesian inference?' },
          { id: 'm46', name: 'What is the base rate fallacy? How do you avoid it?' },
          { id: 'm47', name: 'What is the Monty Hall problem? Explain the solution' },
          { id: 'm48', name: 'What is the birthday paradox? How many people for 50% chance of shared birthday?' },
          { id: 'm49', name: 'What is Simpson\'s paradox? Give an example' },
          { id: 'm50', name: 'What is the prosecutor\'s fallacy?' },
          { id: 'm51', name: 'How do you apply Bayes\' theorem in a spam detection context?' },
          { id: 'm52', name: 'What is the difference between P(A|B) and P(B|A)? Why does it matter?' },
        ],
      },
      {
        id: 'm-expected-value',
        title: 'Expected Value & Variance',
        items: [
          { id: 'm53', name: 'Calculate E[X] for a discrete random variable given a probability distribution' },
          { id: 'm54', name: 'What is E[X+Y] = E[X] + E[Y]? Prove linearity of expectation' },
          { id: 'm55', name: 'What is E[XY] for independent X, Y? What if they are not independent?' },
          { id: 'm56', name: 'What is Var(X) = E[X^2] - (E[X])^2?' },
          { id: 'm57', name: 'What is Var(aX + b) = a^2 * Var(X)?' },
          { id: 'm58', name: 'What is Var(X + Y) = Var(X) + Var(Y) + 2Cov(X,Y)? When does it reduce to Var(X)+Var(Y)?' },
          { id: 'm59', name: 'What is the expected number of trials until success in a geometric distribution?' },
          { id: 'm60', name: 'What is the expected value of a binomial distribution? Of a Poisson distribution?' },
          { id: 'm61', name: 'What is the coupon collector problem and its expected time?' },
          { id: 'm62', name: 'What is the linearity of expectation trick for counting problems?' },
          { id: 'm63', name: 'What is the variance of a uniform distribution? Of a geometric distribution?' },
          { id: 'm64', name: 'What is covariance? What is correlation?' },
        ],
      },
      {
        id: 'm-randomized',
        title: 'Randomized Algorithms',
        items: [
          { id: 'm65', name: 'What is a randomized algorithm? Monte Carlo vs. Las Vegas' },
          { id: 'm66', name: 'What is randomized quicksort and why is it preferred over deterministic quicksort?' },
          { id: 'm67', name: 'What is the coupon collector expected time calculation?' },
          { id: 'm68', name: 'What is a probabilistic method proof? Give an example' },
          { id: 'm69', name: 'What is a random variable concentration bound?', note: 'Markov, Chebyshev, Chernoff bounds' },
          { id: 'm70', name: 'What is the probability that quicksort runs in O(n log n) time?' },
          { id: 'm71', name: 'What is the probability of no collisions when hashing n items into m slots?', note: 'Birthday problem generalization' },
        ],
      },
      {
        id: 'm-coding-applications',
        title: 'Math in Coding Problems',
        items: [
          { id: 'm72', name: 'Implement modular exponentiation: a^b mod m efficiently', note: 'O(log b) using exponentiation by squaring' },
          { id: 'm73', name: 'What is Fermat\'s little theorem? How is it used for modular inverse?' },
          { id: 'm74', name: 'Implement modular inverse using Fermat\'s little theorem' },
          { id: 'm75', name: 'What is the extended Euclidean algorithm? Implement it' },
          { id: 'm76', name: 'What is the Chinese Remainder Theorem? Solve a CRT system' },
          { id: 'm77', name: 'What is the Sieve of Eratosthenes? Complexity analysis' },
          { id: 'm78', name: 'What is prime factorization? Implement and analyze' },
          { id: 'm79', name: 'What is the greatest common divisor (GCD)? Implement Euclidean algorithm' },
          { id: 'm80', name: 'What is the least common multiple (LCM)? How does it relate to GCD?' },
          { id: 'm81', name: 'How many trailing zeros does n! have? (related to count of factors 2 and 5)' },
          { id: 'm82', name: 'What is the formula for the number of ways to climb n stairs (1 or 2 steps)?' },
          { id: 'm83', name: 'How do you compute the number of unique BSTs with n nodes?' },
          { id: 'm84', name: 'What is the formula for the number of permutations with duplicates?' },
          { id: 'm85', name: 'What is the Fibonacci sequence? What is the closed-form (Binet\'s formula)?' },
          { id: 'm86', name: 'What is the sum of the first n natural numbers? Sum of squares? Sum of cubes?' },
          { id: 'm87', name: 'What is the geometric series formula? When does it apply?' },
          { id: 'm88', name: 'What is the pigeonhole principle application in a coding interview context?' },
          { id: 'm89', name: 'How do you check if a number is a power of 2 using bit manipulation?' },
          { id: 'm90', name: 'What is the probability that two randomly chosen numbers are coprime?' },
        ],
      },
      {
        id: 'm-statistics',
        title: 'Statistics (Interview Relevance)',
        items: [
          { id: 'm91', name: 'What is the difference between mean, median, and mode?' },
          { id: 'm92', name: 'What is standard deviation and variance?' },
          { id: 'm93', name: 'What is a percentile? How is the median related to percentiles?' },
          { id: 'm94', name: 'What is the difference between population and sample statistics?' },
          { id: 'm95', name: 'What is a p-value? What does it mean if p < 0.05?' },
          { id: 'm96', name: 'What is the difference between correlation and causation?' },
          { id: 'm97', name: 'What is a confidence interval?' },
          { id: 'm98', name: 'What is the difference between Type I and Type II error?' },
          { id: 'm99', name: 'What is A/B testing? How do you design an A/B test?' },
          { id: 'm100', name: 'How do you calculate statistical significance for an A/B test?' },
        ],
      },
      {
        id: 'm-brain-teasers',
        title: 'Interview Brain Teasers',
        items: [
          { id: 'm101', name: 'You have 100 doors in a row. Toggle door i if i is divisible by pass number. Which are open at end?' },
          { id: 'm102', name: 'You have a 5-gallon and 3-gallon jug. Measure exactly 4 gallons.' },
          { id: 'm103', name: '12 balls, one is a different weight (heavier or lighter). Find it in 3 weighings on a balance.' },
          { id: 'm104', name: '100 prisoners, 100 boxes, each with a number 1-100, find your number. Strategy with 50% success.' },
          { id: 'm105', name: 'Two bottles, one fills in 4 min, one in 7 min. Measure exactly 9 minutes.' },
          { id: 'm106', name: 'Three light switches, three bulbs in another room. One visit to determine which switch controls which bulb.' },
          { id: 'm107', name: 'Poisoned wine bottles, 24 hours to test, 10 rats. Find 1 poisoned bottle among 1000.' },
          { id: 'm108', name: 'The 100 prisoners and 100 drawers problem — find the optimal strategy with ~31% success' },
        ],
      },
    ],
  },
};
